# -*- coding: utf-8 -*-
"""MP3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19FX0BhRDHoqfJqdti26TqUi8getBJ1Wk

# Miniproyecto 3: ¿Te gustaría ser *Data Scientist Senior*?
#### **Curso:** Introducción a Minería de Datos y Machine Learning

---

**¡Tienes una oferta de trabajo!**

Una empresa se enteró de tu **excelente** trabajo como *Data Scientist Junior* en **AMAZOFF**.

¡Quieren que trabajes con ellos como ***Data Scientist Senior***!

Para la entrevista de trabajo, te han pedido que utilices tus poderes de ***Machine Learning*** en sus bases de datos.

**¿Estás listo para el reto?**

# ¿Qué empresa te quiere en su equipo?

En este MP3 deberás buscar una base de datos y aplicar tus conocimientos de *Machine Learning*.

Una vez elegida la base de datos, deberás inventar una empresa ficticia que te busca para el puesto de *Data Scientist Senior*.

La empresa debe de tener sentido con los datos y lo que quieres predecir usando *Machine Learning*.

## ¿Cómo elegir la base de datos?

Puedes utilizar cualquier base de datos que esté publicada en internet de forma libre. Esta base de datos debe por lo menos cumplir con:

- Tener al menos 1000 filas después de limpiarla.
- Tener al menos 5 columnas con información relevante (no cuentan: *ids*, *index*, etc.) después de limpiarla.
- No tener consideraciones éticas graves. Ejemplo: datos privados de una empresa real.
- Debe tener al menos una columna (aparte de las 5 relevantes) para predecir (columna `label`o `target`).
- El ejercio contempla solo una base de datos. Si tus datos vienen originalmente en más de una, deberás juntarlos (ejemplo: `join`, `merge`, etc.) en la pregunta 1. Debes cargar todos los datos necesarios en la sección de **Preámbulo**.

# Define tu empresa

> **¡No olvides elegir tus datos primero!**

- **Nombre de la empresa**: BIODATASCIENCE
- **Descripción de la empresa**: Empresa de análisis de datos biológicos.

# Pauta de Evaluación

Este MP3 está enfocado en responder preguntas de negocio relevantes para tu nueva empresa (creada por ti).

### Preguntas de Negocio

1. (10 puntos) ¿Cargaste los datos? ¡Toca limpiarlos! La empresa no ha tocado esos datos. ¿Se los puedes explicar?
2. (15 puntos) Datos limpios. Pues, es hora de un... ¡Análisis Exploratorio de Datos!
3. (10 puntos) ¡Vamos con el ML... ¿Qué? ¿Hay que preparar los datos primero?
4. (20 puntos) ¡Grupos everywhere!
5. (25 puntos) ¿Podemos predecir algo con estos datos? Demostremos nuestra experiencia.
6. (20 puntos) ¿Puedes explicar mejor tus resultados? ¡De Junior a Senior!

### Tener en consideración:

En caso de que el código esté bien, pero no se responda (usando celdas de texto) la pregunta de negocio (sección **Explicación**), **se asignará máximo la mitad de puntos** de esa pregunta.

> # ¡NO OLVIDES GUARDAR Y SUBIR EL NOTEBOOK A LA PLATAFORMA CUANDO TERMINES! FORMATO .ipynb

> # ¡NO OLVIDES SUBIR LOS DATOS ORIGINALES A LA PLATAFORMA!

# Preámbulo
"""

# Agrega todas las librerias necesarias para el proyecto en su sección correspondiente

# Clustering
from sklearn.cluster import KMeans

# Machine Learning
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

# General Data Science
from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

#from google.colab import drive
#drive.mount('/content/drive')

# Esta configuración permite que los dataframes se muestren completos.
pd.set_option('display.max_columns', None)

# PARÁMETROS (puedes modificar esta sección)

DATA_PATH = './' # Si tienes el archivo en otro lugar, cámbialo.
RANDOM_STATE = 0 # ¡Cámbialo a tu número favorito!

# Esta celda se encarga de cargar los datos. ¿La necesitas modificar? ¡Adelante!

df = pd.read_csv(DATA_PATH + 'usa_county_wise.csv')
print(f'{df.shape[0]} rows x {df.shape[1]} columns')
df.head(5)

# ¿Necesitas más celdas antes de empezar a trabajar? ¡Agrega todas las que necesites!
# No olvides que en la pregunta 1 es donde debes hacer la limpieza de datos.

# [ AGREGA AQUÍ TU CÓDIGO ]

"""# 1. ¿Cargaste los datos? ¡Toca limpiarlos! La empresa no ha tocado esos datos. ¿Se los puedes explicar?

⁉️ **Consideración:** Asegúrate que no haya datos faltantes, que estén en el formato o tipo de dato correctos, que no haya inconsistencias, que puedas estar seguro que los datos están listos para ser usados. No olvides explicar todas tus decisiones.

ℹ️ **HINT 1:** ¿Necesitas crear nuevas columnas? ¿Tienes datos con muchas categorías? ¿Sobran columnas?

ℹ️ **HINT 2:** Recuerda que esta sección debe cumplir con los criterios para elegir la base de datos.

ℹ️ **HINT 3:** Toma de inspiración la pregunta 2 del MP1.

---

✅ **Explicación:**

[ AGREGA TU RESPUESTA ACÁ ]
"""

#Se modifica nombre de las columnas:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.split("_").str[0].str.strip()
df

df.columns

for col in df.columns:
    print(f'{col}: {df[col].nunique()} unique values')

df.dtypes

df["combined"]=df["combined"].str.replace(", ",",")
df[df["province"]+","+df["country"]!=df["combined"]]

df = df.drop(columns=['uid', 'iso2', 'iso3', 'code3', 'fips', 'admin2']) #Se eliminan ya que no aportan informacion nueva
df = df.drop(columns=['country']) #Se elimina ya que existe una sola ocurrencia: US
df["combined"] = df["combined"].str.split(",US").str[0].str.strip()
df.head(5)

#Definimos un DF2 tal que considere solo las columnas provincia y combinada, y solo en las que la 1era. parte de combinada sea distinto a provincia:
df2=df[df["combined"].str.split(",").str[0].str.strip()!=df["province"]].drop(columns=["lat","long","date","confirmed","deaths"])
df2

#De DF2 muestreme donde la provincia sea distinta a la 2da. parte de combinada:
df2[df2["province"]!=df2["combined"].str.split(",").str[1].str.strip()]

#Como la consulta anterior no muestra datos, la columna provincia es redundante y se elimina:
df = df.drop(columns=["province"])
df

df.rename(columns={'combined':'city'},inplace=True,errors='ignore')
df.dtypes

for col in df.columns:
    print(f'{col}: {df[col].nunique()} unique values')

df.lat.unique()

df.long.unique()

df.city.unique()

df.date.unique()

df.info()

#Separamos fecha en dd,mm,yyyy:
df["dddate"]=df["date"].str.split("/").str[1].astype(int)
df["mmdate"]=df["date"].str.split("/").str[0].astype(int)
df["yydate"]=df["date"].str.split("/").str[2].astype(int)
df.drop(columns=["date"],inplace=True,errors='ignore')
df

df.city.unique()

#Se quitan espacios y comas a las ciudades:
df.city=df.city.str.replace(",","_").str.replace(" ","_")
df.city.unique()

#La siguiente instruccion falla ya que utiliza toda la RAM disponible de Google Colab, por lo que se quita del programa:
#df_encoded = pd.get_dummies(df, columns=['city'],dtype=int) #Convierte dato city en boolanos de 0 y 1
#Se prefiere eliminar city por lo anterior, y usar solo las coordenadas de latitud y longitud:
df = df.drop(columns=['city'])
df

correct_order = ["lat","long","yydate","mmdate","dddate","confirmed","deaths"]
df = df[correct_order] #Orden de columnas correcto
df

df.info()

"""# 2. Datos limpios. Pues, es hora de un... ¡Análisis Exploratorio de Datos!

⁉️ **Consideración:** ¡Es hora del EDA! Es importante entender muy bien que **información** contienen tus datos. Para esto, considerando las necesidades de tu empresa, plantearás 5 preguntas interesantes para ella que se puedan responder al analizar tus datos.

ℹ️ **HINT 1 :** Busca preguntas relevantes y no triviales. Utiliza gráficos, estadísticas, lo que se ocurra para explotar la información de los datos.

ℹ️ **HINT 2:** Inspírate en las preguntas 3 y 4 del MP1.

---

✅ **Explicación:**

- **Pregunta 1: ¿[ PREGUNTA ACÁ ]?**

    [ AGREGA TU RESPUESTA ACÁ ]

- **Pregunta 2: ¿[ PREGUNTA ACÁ ]?**

    [ AGREGA TU RESPUESTA ACÁ ]

- **Pregunta 3: ¿[ PREGUNTA ACÁ ]?**

    [ AGREGA TU RESPUESTA ACÁ ]

- **Pregunta 4: ¿[ PREGUNTA ACÁ ]?**

    [ AGREGA TU RESPUESTA ACÁ ]

- **Pregunta 5: ¿[ PREGUNTA ACÁ ]?**

    [ AGREGA TU RESPUESTA ACÁ ]
"""

# PREGUNTA 1: ¿Cuales son las estadisticas descriptivas del dataframe?
df.describe()

# PREGUNTA 2: ¿Cual es la cantidad de fallecidos en relacion a la latitud?
# Gráfico 1: GRÁFICO DE DISPERSIÓN DE MUERTES ASOCIADAS A LA LATITUD.
# Crear una "parcela" de dispersión usando Seaborn:
sns.scatterplot(x="lat", y="deaths", data=df) #Relacion entre latitud y muertes
# Guardar figura:
plt.savefig("scatterplot1.png")
# Mostrar la trama:
plt.show()

# PREGUNTA 3: ¿Cual es la cantidad de fallecidos en relacion a la longitud?
# Gráfico 2: GRÁFICO DE DISPERSIÓN DE MUERTES ASOCIADAS A LA LONGITUD.
# Crear una "parcela" de dispersión usando Seaborn:
sns.scatterplot(x="long", y="deaths", data=df) #Relacion entre longitud y muertes
# Guardar figura:
plt.savefig("scatterplot2.png")
# Mostrar la trama:
plt.show()

## PREGUNTA 4: ¿Cual es la cantidad de contagiados en relacion al numero de mes?
## Gráfico 3: GRÁFICO DE BARRAS DE NÚMERO DE CONTAGIADOS VERSUS EL MES (INDEPENDIENTE DEL AÑO).
## Filtrar los datos para incluir únicamente a los sobrevivientes:
#lproductosvendidos = df["product"].value_counts() #Lista de productos entregados
## Crear un grafico de barra usando Seaborn:
#sns.barplot(x=lproductosvendidos.index, y=lproductosvendidos.values)
## Establezca el título de la trama y etiquetas de eje:
#plt.title("Productos vendidos")
#plt.xlabel("Productos")
#plt.ylabel("Cantidad")
## Guardar figura:
#plt.savefig("bar-plot.png")
## Mostrar la trama:
#plt.show()
