# -*- coding: utf-8 -*-
"""MP3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19FX0BhRDHoqfJqdti26TqUi8getBJ1Wk

# Miniproyecto 3: ¿Te gustaría ser *Data Scientist Senior*?
#### **Curso:** Introducción a Minería de Datos y Machine Learning

---

**¡Tienes una oferta de trabajo!**

Una empresa se enteró de tu **excelente** trabajo como *Data Scientist Junior* en **AMAZOFF**.

¡Quieren que trabajes con ellos como ***Data Scientist Senior***!

Para la entrevista de trabajo, te han pedido que utilices tus poderes de ***Machine Learning*** en sus bases de datos.

**¿Estás listo para el reto?**

# ¿Qué empresa te quiere en su equipo?

En este MP3 deberás buscar una base de datos y aplicar tus conocimientos de *Machine Learning*.

Una vez elegida la base de datos, deberás inventar una empresa ficticia que te busca para el puesto de *Data Scientist Senior*.

La empresa debe de tener sentido con los datos y lo que quieres predecir usando *Machine Learning*.

## ¿Cómo elegir la base de datos?

Puedes utilizar cualquier base de datos que esté publicada en internet de forma libre. Esta base de datos debe por lo menos cumplir con:

- Tener al menos 1000 filas después de limpiarla.
- Tener al menos 5 columnas con información relevante (no cuentan: *ids*, *index*, etc.) después de limpiarla.
- No tener consideraciones éticas graves. Ejemplo: datos privados de una empresa real.
- Debe tener al menos una columna (aparte de las 5 relevantes) para predecir (columna `label`o `target`).
- El ejercio contempla solo una base de datos. Si tus datos vienen originalmente en más de una, deberás juntarlos (ejemplo: `join`, `merge`, etc.) en la pregunta 1. Debes cargar todos los datos necesarios en la sección de **Preámbulo**.

# Define tu empresa

> **¡No olvides elegir tus datos primero!**

- **Nombre de la empresa**: **BIODATASCIENCE RESEARCHES**
- **Descripción de la empresa**: Empresa internacional dedicada al análisis de datos biológicos.

# Pauta de Evaluación

Este MP3 está enfocado en responder preguntas de negocio relevantes para tu nueva empresa (creada por ti).

### Preguntas de Negocio

1. (10 puntos) ¿Cargaste los datos? ¡Toca limpiarlos! La empresa no ha tocado esos datos. ¿Se los puedes explicar?
2. (15 puntos) Datos limpios. Pues, es hora de un... ¡Análisis Exploratorio de Datos!
3. (10 puntos) ¡Vamos con el ML... ¿Qué? ¿Hay que preparar los datos primero?
4. (20 puntos) ¡Grupos everywhere!
5. (25 puntos) ¿Podemos predecir algo con estos datos? Demostremos nuestra experiencia.
6. (20 puntos) ¿Puedes explicar mejor tus resultados? ¡De Junior a Senior!

### Tener en consideración:

En caso de que el código esté bien, pero no se responda (usando celdas de texto) la pregunta de negocio (sección **Explicación**), **se asignará máximo la mitad de puntos** de esa pregunta.

> # ¡NO OLVIDES GUARDAR Y SUBIR EL NOTEBOOK A LA PLATAFORMA CUANDO TERMINES! FORMATO .ipynb

> # ¡NO OLVIDES SUBIR LOS DATOS ORIGINALES A LA PLATAFORMA!

# Preámbulo
"""

# Agrega todas las librerias necesarias para el proyecto en su sección correspondiente

# Clustering
from sklearn.cluster import KMeans

# Machine Learning
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder, StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import AgglomerativeClustering
from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.decomposition import PCA

# General Data Science
from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

#from google.colab import drive
#drive.mount('/content/drive')

# Esta configuración permite que los dataframes se muestren completos.
pd.set_option('display.max_columns', None)

# PARÁMETROS (puedes modificar esta sección)

DATA_PATH = './' # Si tienes el archivo en otro lugar, cámbialo.
RANDOM_STATE = 0 # ¡Cámbialo a tu número favorito!

# Esta celda se encarga de cargar los datos. ¿La necesitas modificar? ¡Adelante!

df = pd.read_csv(DATA_PATH + 'usa_county_wise.csv')
print(f'{df.shape[0]} rows x {df.shape[1]} columns')
df.head(5)

# ¿Necesitas más celdas antes de empezar a trabajar? ¡Agrega todas las que necesites!
# No olvides que en la pregunta 1 es donde debes hacer la limpieza de datos.

# [ AGREGA AQUÍ TU CÓDIGO ]

"""# 1. ¿Cargaste los datos? ¡Toca limpiarlos! La empresa no ha tocado esos datos. ¿Se los puedes explicar?

⁉️ **Consideración:** Asegúrate que no haya datos faltantes, que estén en el formato o tipo de dato correctos, que no haya inconsistencias, que puedas estar seguro que los datos están listos para ser usados. No olvides explicar todas tus decisiones.

ℹ️ **HINT 1:** ¿Necesitas crear nuevas columnas? ¿Tienes datos con muchas categorías? ¿Sobran columnas?

ℹ️ **HINT 2:** Recuerda que esta sección debe cumplir con los criterios para elegir la base de datos.

ℹ️ **HINT 3:** Toma de inspiración la pregunta 2 del MP1.

---

✅ **Explicación:**

Los datos recabados corresponden a una base de datos sobre la infección de COVID-19 en los Estados Unidos, que puede localizarse en: https://www.kaggle.com/datasets?search=covid (**usa_county_wise.csv**), que contiene los casos confirmados y las muertes reportadas para diferentes localidades del país del hemisferio Norte, con sus respectivas latitudes y longitudes geográficas.
"""

#Se modifica nombre de las columnas:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.split("_").str[0].str.strip()
df

df.columns

for col in df.columns:
    print(f'{col}: {df[col].nunique()} unique values')

df.dtypes

df["combined"]=df["combined"].str.replace(", ",",")
df[df["province"]+","+df["country"]!=df["combined"]]

df = df.drop(columns=['uid', 'iso2', 'iso3', 'code3', 'fips', 'admin2']) #Se eliminan ya que no aportan informacion nueva
df = df.drop(columns=['country']) #Se elimina ya que existe una sola ocurrencia: US
df["combined"] = df["combined"].str.split(",US").str[0].str.strip()
df.head(5)

#Definimos un DF2 tal que considere solo las columnas provincia y combinada, y solo en las que la 1era. parte de combinada sea distinto a provincia:
df2=df[df["combined"].str.split(",").str[0].str.strip()!=df["province"]].drop(columns=["lat","long","date","confirmed","deaths"])
df2

#De DF2 muestreme donde la provincia sea distinta a la 2da. parte de combinada:
df2[df2["province"]!=df2["combined"].str.split(",").str[1].str.strip()]

#Como la consulta anterior no muestra datos, la columna provincia es redundante y se elimina:
df = df.drop(columns=["province"])
df

df.rename(columns={'combined':'city'},inplace=True,errors='ignore')
df.dtypes

for col in df.columns:
    print(f'{col}: {df[col].nunique()} unique values')

df.lat.unique()

df.long.unique()

df.city.unique()

df.date.unique()

df.info()

#Separamos fecha en dd,mm,yyyy:
df["dddate"]=df["date"].str.split("/").str[1].astype(int)
df["mmdate"]=df["date"].str.split("/").str[0].astype(int)
df["yydate"]=df["date"].str.split("/").str[2].astype(int)
df.drop(columns=["date"],inplace=True,errors='ignore')
df

df.city.unique()

#Se quitan espacios y comas a las ciudades:
df.city=df.city.str.replace(",","_").str.replace(" ","_")
df.city.unique()

#La siguiente instruccion falla ya que utiliza toda la RAM disponible de Google Colab, por lo que se quita del programa:
#df_encoded = pd.get_dummies(df, columns=['city'],dtype=int) #Convierte dato city en boolanos de 0 y 1
#Se prefiere eliminar city por lo anterior, y usar solo las coordenadas de latitud y longitud:
df = df.drop(columns=['city'])
df

correct_order = ["lat","long","yydate","mmdate","dddate","confirmed","deaths"]
df = df[correct_order] #Orden de columnas correcto
df

df.info()

"""# 2. Datos limpios. Pues, es hora de un... ¡Análisis Exploratorio de Datos!

⁉️ **Consideración:** ¡Es hora del EDA! Es importante entender muy bien que **información** contienen tus datos. Para esto, considerando las necesidades de tu empresa, plantearás 5 preguntas interesantes para ella que se puedan responder al analizar tus datos.

ℹ️ **HINT 1 :** Busca preguntas relevantes y no triviales. Utiliza gráficos, estadísticas, lo que se ocurra para explotar la información de los datos.

ℹ️ **HINT 2:** Inspírate en las preguntas 3 y 4 del MP1.

---

✅ **Explicación:**

- **Pregunta 1: ¿Cuales son las estadisticas descriptivas del dataframe?**

    Los datos estadísticos muestran que los casos reportados se encuentran bien dispersos entre las zonas de Estados Unidos, todos ellos reportados el año 2020 (min y max de yydate) y entre el 1 de Enero al 31 de Julio de ese año, distribuyéndose en promedio, en torno al mes de Abril (mmdate.avg)

- **Pregunta 2: ¿Cual es la cantidad de contagiados en relacion a la latitud?**

    Se aprecia una mayor concentración de casos confirmados próximo a la latitud 40.

- **Pregunta 3: ¿Cual es la cantidad de fallecidos en relacion a la latitud?**

    Se aprecia una mayor concentración de fallecidos próximo también a la latitud 40.

- **Pregunta 4: ¿Cual es la cantidad de contagiados en relacion a la longitud?**

    Se aprecia una mayor concentración de casos confirmados próximo a la longitud -75.

- **Pregunta 5: ¿Cual es la cantidad de fallecidos en relacion a la longitud?**

    Se aprecia una mayor concentración de fallecidos próximo a la longitud -75.
"""

# PREGUNTA 1: ¿Cuales son las estadisticas descriptivas del dataframe?
df.describe()

# PREGUNTA 2: ¿Cual es la cantidad de contagiados en relacion a la latitud?
# Gráfico 1: GRÁFICO DE DISPERSIÓN DE CONTAGIOS CONFIRMADOS ASOCIADOS A LA LATITUD.
# Crear una "parcela" de dispersión usando Seaborn:
sns.scatterplot(x="lat", y="confirmed", data=df) #Relacion entre latitud y contagios confirmados
# Guardar figura:
plt.savefig("scatterplot1.png")
# Mostrar la trama:
plt.show()

# PREGUNTA 3: ¿Cual es la cantidad de fallecidos en relacion a la latitud?
# Gráfico 2: GRÁFICO DE DISPERSIÓN DE MUERTES ASOCIADAS A LA LATITUD.
# Crear una "parcela" de dispersión usando Seaborn:
sns.scatterplot(x="lat", y="deaths", data=df) #Relacion entre latitud y muertes
# Guardar figura:
plt.savefig("scatterplot2.png")
# Mostrar la trama:
plt.show()

# PREGUNTA 4: ¿Cual es la cantidad de contagiados en relacion a la longitud?
# Gráfico 3: GRÁFICO DE DISPERSIÓN DE CONTAGIOS CONFIRMADOS ASOCIADAS A LA LONGITUD.
# Crear una "parcela" de dispersión usando Seaborn:
sns.scatterplot(x="long", y="confirmed", data=df) #Relacion entre longitud y contagias confirmados
# Guardar figura:
plt.savefig("scatterplot3.png")
# Mostrar la trama:
plt.show()

# PREGUNTA 5: ¿Cual es la cantidad de fallecidos en relacion a la longitud?
# Gráfico 4: GRÁFICO DE DISPERSIÓN DE MUERTES ASOCIADAS A LA LONGITUD.
# Crear una "parcela" de dispersión usando Seaborn:
sns.scatterplot(x="long", y="deaths", data=df) #Relacion entre longitud y muertes
# Guardar figura:
plt.savefig("scatterplot4.png")
# Mostrar la trama:
plt.show()

"""# 3. ¡Vamos con el ML... ¿Qué? ¿Hay que preparar los datos primero?

⁉️ **Consideración:** En las siguientes preguntas harás clusterización y aprendizaje de máquina... prepara tus datos pensando en los modelos que utilizarás. Acá se toman los datos limpios y se pasan a numérico, se cambian las escalas, se agregan columnas para mejorar los resultados de los modelos, etc. Justifica todas tus decisiones.

ℹ️ **HINT:** ¿*Encoding*? ¿Normalización? ¿*Feature Engineering*?

---

✅ **Explicación:**

- **Normalización:** En caso de datos muy dispersos, se ocupa un método que permita tener los datos más comprensibles y analizables.
- **Estandarización:** En caso de tener datos provenientes de fuentes distintas, se busca un método que permita transformar tal dato a un criterio común.
"""

#Eliminar dato irrelevante:
df=df.drop(columns=["yydate"]) #Eliminamos yydate ya que no aporta información relevante.
df.head(3)

# Normalización: Para establecer las distiancias, se deben normalizar los datos de modo de permitir su comparacion:
minmax = MinMaxScaler()
df['minmax_lat'] = minmax.fit_transform(df[['lat']])
df['minmax_long'] = minmax.fit_transform(df[['long']])
df['minmax_mmdate'] = minmax.fit_transform(df[['mmdate']])
df['minmax_dddate'] = minmax.fit_transform(df[['dddate']])
df['minmax_confirmed'] = minmax.fit_transform(df[['confirmed']])
df=df.drop(columns=['lat','long','mmdate','dddate','confirmed']) #Se eliminan columnas redundantes por el paso anterior
df=df[['minmax_lat','minmax_long','minmax_mmdate','minmax_dddate','minmax_confirmed','deaths']] #Reordenamos columnas
df.head(5)

# Estandarización: No se aplica, ya que los datos proceden todos de una misma fuente.
df

"""# 4. ¡Grupos everywhere!

⁉️ **Consideración:** Utiliza técnicas de clusterización para encontrar grupos dentro de tus datos. Recuerda colorear tus gráficos correctamente para que podamos ver los grupos. Sí, debes de graficar tus resultados. ¿En 2D, 3D, 4D? Queda a tu decisión. Recuerda que solo puedes usar métodos de clusterización de `sklearn`.

ℹ️ **HINT 1:** No olvides que cada método es diferente. ¿Justificarás por qué elegiste ese método?

ℹ️ **HINT 2:** No olvides explicar cómo eliges tus hiperparámetros.

ℹ️ **HINT 3:** ¿No encuentras grupos? ¿Sabías que PCA y otras técnicas de reducción de dimensionalidad son útiles para *clustering*?

---

✅ **Explicación:**

Se intenta realizar un proceso de aprendizaje de máquina no supervisado, mediante clusterización. Se prueba inicialmente con el algoritmo de K-Means en Google Colab, no obstante, la gran cantidad de datos suministrados (cerca de 630 mil filas de datos) hace que el algoritmo se ejecute durante horas. Se muestra a continuación una clusterización aplicando el método de clustering jerárquico. No obstante, la gran cantidad de datos suministrados impide que el algoritmo se ejecute correctamente: "**Unable to allocate 1.43 TiB for an array with shape (197141449240,) and data type float64**" (No se pueden asignar 1,43 TiB para una matriz con forma (197141449240,) y tipo de datos float64).
"""

df.isna().sum() #Verificamos ausencia de datos nulos:

# Dividimos los datos en el conjunto X de entrada, e Y de salida:
x = df[['minmax_lat','minmax_long','minmax_mmdate','minmax_dddate','minmax_confirmed']]
y = df[['deaths']]
x.shape

x_scaled = StandardScaler().fit_transform(x) #Se aplicara analisis de componentes principales
x_scaled

pca = PCA(n_components=3) #Analisis de 3 componentes principales
pca_f = pca.fit_transform(x_scaled)
X = pca_f.copy()
X.shape

link = linkage(X, 'ward')
plt.figure(figsize=(10, 10))
dendrogram(link) #Dendograma

#Clustering Jerárquico:
cluster = AgglomerativeClustering(n_clusters=4, affinity='euclidean', linkage='ward')
cluster.fit_predict(X)

y_cj = cluster.labels_
print(y_cj)

#Visualización Clustering Jerárquico:
fig, ax = plt.subplots(nrows = 3,ncols = 2,figsize = (10,10), dpi=100)
ax[0,0].set_title('Clustering Jerárquico')
l = ax[0,0].scatter(X[:,0], X[:,1],
           c= y_cj,
           s=60,
           alpha=0.3, cmap='rainbow')
ax[1,0].scatter(X[:,0], X[:,2],
           c= y_cj,
           s=60,
           alpha=0.3, cmap='rainbow')
ax[2,0].scatter(X[:,1], X[:,2],
           c= y_cj,
           s=60,
           alpha=0.3, cmap='rainbow')

ax[0,1].set_title('Original')
l2 = ax[0,1].scatter(X[:,0], X[:,1],
           c= y,
           s=60,
           alpha=0.3, cmap='rainbow')
ax[1,1].scatter(X[:,0], X[:,2],
           c= y,
           s=60,
           alpha=0.3, cmap='rainbow')
ax[2,1].scatter(X[:,1], X[:,2],
           c= y,
           s=60,
           alpha=0.3, cmap='rainbow')
legend1 = ax[0,0].legend(*l.legend_elements(),
                    loc="upper left", title="Score")
ax[0,0].add_artist(legend1)

legend2 = ax[0,1].legend(*l2.legend_elements(),
                    loc="upper left", title="Score")
ax[0,1].add_artist(legend2)

fig = plt.figure(figsize = (8, 8),dpi=100)
ax = plt.axes(projection ="3d")
l3d = ax.scatter3D(X[:,0], X[:,1], X[:,2], c=y_cj,alpha=0.5, edgecolor='k',s=50, cmap='rainbow')
ax.set_title('Clustering Jerárquico',fontsize=20)

ax.legend(l3d.legend_elements()[0],[0,1,2,3])

X[:,0]

X[:,1]

X[:,2]

fig = plt.figure(figsize = (8, 8),dpi=100)
ax = plt.axes(projection ="3d")
l3d_ = ax.scatter3D(X[:,0], X[:,1], X[:,2], c=y,alpha=0.5, edgecolor='k',s=50, cmap='rainbow')
ax.set_title('Datos originales',fontsize=20)

ax.legend(l3d_.legend_elements()[0],[0,1,2,3])

"""# 5. ¿Podemos predecir algo con estos datos? Demostremos nuestra experiencia.

⁉️ **Consideración:** Es la hora de aplicar modelos de clasificación o regresión (`sklearn`) a los datos. Enfócate en ser ordenado y seguir todos los pasos: datos, entrenamiento, validación, testeo, interpretación, etc. Debes de explicar a fondo tus decisiones de modelo, parámetros, interpretación de resultados, medidas de rendimiento, etc.

ℹ️ **HINT 1:** ¿Habías escuchado de Validación Cruzada? ¿Has escuchado de `GridSearchCV`?

ℹ️ **HINT 2:** ¿Te fjaste en el *overfitting*?

ℹ️ **HINT 3:** ¿Por qué elegiste ese modelo? Puedes utilizar cualquier modelo de `sklearn`.

ℹ️ **HINT 4:** Se recomienda que comparen varios modelos. ¿Leíste la documentación de `sklearn`?

---

✅ **Explicación:**

Se intenta ejecutar un clasificador RandomForest, sin embargo, al ejecutar el proceso predictor a partir de los datos de validación, la máquina se colapsa. Esto, aparentemente por la gran cantidad de datos suministrados, según lo explicado en la pregunta anterior.
"""

x_train_val, x_test, y_train_val, y_test = train_test_split(x, y, test_size=0.2, random_state=RANDOM_STATE, shuffle=True)
x_train, x_val, y_train, y_val = train_test_split(x_train_val, y_train_val, test_size=0.2, random_state=RANDOM_STATE, shuffle=True)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# rf = RandomForestClassifier(
#     n_estimators=100,           #Num. arboles, 100 por defecto
#     max_depth=3,                #Profundidad del arbol
#     max_features=3,             #Num. maximo de caracteristicas a considerar
#     #criterion="gini",          #Criterio Gini, por defecto
#     random_state=RANDOM_STATE,
#     n_jobs=-1                   #Todos los procesadores
# )
# rf.fit(x_train, y_train)

## ¡NO DESCOMENTAR Y EJECUTAR ESTA CELDA! YA QUE COLAPSA LA MAQUINA...
#y_val_pred = rf.predict(x_val)
#
#print('[Random Forest] Check Overfitting with Accuracy')
#print(f'RF: train={accuracy_score(y_train, rf.predict(x_train)):.4f} val={accuracy_score(y_val, y_val_pred):.4f}')

"""# 6. ¿Puedes explicar mejor tus resultados? ¡De Junior a Senior!

⁉️ **Consideración:** Para pasar de ser una *Data Scientist Junior* a *Senior* deberás ser muy bueno para interpretar y mejorar los resultados de tu modelo. ¿Qué otras mediciones puedes utilizar? ¿Cómo puedes modificar tus datos? ¿Qué datos te faltan? ¿Qué impacta más a tu predicción? ¿Por qué hay métricas más importantes que otras? ¡Y muchas preguntas más! Ahonda en los resultados de tus modelos.

ℹ️ **HINT 1:** ¿Qué otras métricas existen? ¿Matrices de confusión? ¿Por qué hay clases que funcionan peor?

ℹ️ **HINT 2:** ¿Consideraste la reducción de dimensionalidad?

ℹ️ **HINT 3:** ¿Conoces la librería `SHAP`? ¿O los *Partial Dependece Plots*?

---

✅ **Explicación:**

[ AGREGA TU RESPUESTA ACÁ ]
"""

# [ AGREGA AQUÍ TU CÓDIGO ] ¿Necesitas más celdas? ¡Adelante!

# [ AGREGA AQUÍ TU CÓDIGO ] ¿Necesitas más celdas? ¡Adelante!

# [ AGREGA AQUÍ TU CÓDIGO ] ¿Necesitas más celdas? ¡Adelante!

"""> # ¡NO OLVIDES GUARDAR Y SUBIR EL NOTEBOOK A LA PLATAFORMA CUANDO TERMINES! FORMATO .ipynb

> # ¡NO OLVIDES SUBIR LOS DATOS ORIGINALES A LA PLATAFORMA!
"""