# -*- coding: utf-8 -*-
"""MP2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HTy6exDtCcrQxPJDrKNR89r5_NLY8Y-Q

# Miniproyecto 2: Machine Learning con Valor
#### **Curso:** Introducción a Minería de Datos y Machine Learning

---

**¡Felicidades por tu excelente trabajo en el MP1!**

Tu labor en el preprocesamiento de la base de datos ha causado un gran impacto en **AMAZOFF**.

El equipo de Customer Experience ha quedado impresionado con tu habilidad para transformar datos sucios en información
útil y ahora quieren aprovechar tus talentos para enfrentar un nuevo desafío.

Nos han pedido desarrollar un **Predictor de Ratings de Pedidos** utilizando los datos preprocesados de ratings de
pedidos de nuestra plataforma de e-commerce.
"""

#from google.colab import drive
#drive.mount('/content/drive')

"""# Pauta de Evaluación

Este MP2 está enfocado en responder preguntas de negocio relevantes para **AMAZOFF**.

### Preguntas de Negocio

1. (15 puntos) El equipo necesita extraer la máxima información de los datos. ¿Cómo modificarías la base de datos para ser usada con modelos de ML?
2. (15 puntos) ¡Wow! Gran *feature engineering*. Toca armar tu set para entrenar el modelo. ¿Podrías generar gráficas para el equipo de Customer Experience que expliquen mejor los datos nuevos? ¡No olvides explicarlas!
3. (10 puntos) Dicen que se pueden encontrar patrones en tus datos de entrenamiento. ¿Qué patrones encuentras en los pedidos? ¿Cómo pueden ser de utilidad para mejorar las ventas de AMAZOFF?
4. (25 puntos) ¡Viva el ML! Toca predecir la satisfacción del cliente. ¿Es posible predecir bien el `rating_class`?
5. (20 puntos) El equipo de Customer Experience dice que un solo modelo no es suficiente. ¿Podrías implementar otro?
6. (15 puntos) ¡Dos modelos! Eso es genial. ¿Qué modelo funcionó peor? ¿Si utilizas PCA podría mejor?

### Tener en consideración:

En caso de que el código esté bien, pero no se responda (usando celdas de texto) la pregunta de negocio (sección **Explicación**), **se asignará máximo la mitad de puntos** de esa pregunta.

El miniproyecto está diseñado para completar código. Suba el notebook solo con el código para responder la pregunta de negocio.

> # ¡NO OLVIDES GUARDAR Y SUBIR EL NOTEBOOK A LA PLATAFORMA CUANDO TERMINES! FORMATO .ipynb

# Preámbulo

**¡Cuidado!** En esta sección solo puedes modificar la sección de PÁRAMETROS.
"""

# ¡No modificar esta celda! No está permitido usar librerías adicionales.

# Association Rules
from mlxtend.frequent_patterns import apriori, association_rules

# Machine Learning
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA

# General Data Science
from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# Esta configuración permite que los dataframes se muestren completos.
pd.set_option('display.max_columns', None)

# PARÁMETROS (puedes modificar esta sección)

DATA_PATH = 'ecommerce.csv' # Si tienes el archivo en otro lugar, cámbialo.
RANDOM_STATE = 0 # ¡Cámbialo a tu número favorito!

# ¡No modificar! Esta celda se encarga de cargar los datos.
df = pd.read_csv(DATA_PATH)
df.purchased = pd.to_datetime(df.purchased)
df.delivered = pd.to_datetime(df.delivered)
df.estimated_delivery = pd.to_datetime(df.estimated_delivery)
print(f'{df.shape[0]} rows x {df.shape[1]} columns')
df.head(5)

# ¿Cuántos valores únicos hay en cada columna?
for col in df.columns:
    print(f'{col}: {df[col].nunique()} unique values')

df.dtypes

df.city.unique()

df.state.unique()

df.category.unique()

df.payment.unique()

print (f"{np.min(df.purchased)} - {np.max(df.purchased)}")

print (f"{np.min(df.delivered)} - {np.max(df.delivered)}")

print (f"{np.min(df.estimated_delivery)} - {np.max(df.estimated_delivery)}")

df.rating.unique()

"""# 1. El equipo necesita extraer la máxima información de los datos. ¿Cómo modificarías la base de datos para ser usada con modelos de ML?

⁉️ **Consideración:** La última celda de esta sección es la de cálculo de `rating_class`, mantener el orden. Agregar las celdas para modificar
los datos, antes de esta. No olvides modificar el código para calcular la clase de rating.

ℹ️ **HINT:** Utiliza una celda para cada columna. ¿Qué columnas no sirven? ¿Qué columnas necesito que sean números? ¿Nuevas columnas?

📖 **Referencia Externa:** [Feature Engineering](https://www.freecodecamp.org/news/feature-engineering-techniques-for-structured-data/).

---

✅ **Explicación:**

Se lleva a cabo una transformación de datos, desde una forma no numérica a numérica, esto es, a valores enteros. Tales nuevos valores facilitarán el entrenamiento para el aprendizaje automático, que permitirá a la máquina hacer una mejor clasificación a la hora de hacer, por parte de ésta, una predicción sobre los datos que se le suministren. Para hacer esta transformación se aplica un criterio binario 0 ó 1, para la mayoría de las características, para indicar la presencia (1) o ausencia (0) de una determinada feature. Se aplica este criterio dada la imposibilidad de establecer un valor cuantificable que indique la distancia entre dos o más características de tipo string. Distinto es el caso de las fechas, en el que se toma como valor numérico, los nanosegundos correspondientes a cada una.
"""

###City: array(['unknown', 'uberlandia', 'guarulhos', 'sao paulo', 'sao goncalo',
###    'belo horizonte', 'curitiba', 'porto alegre', 'rio de janeiro',
###    'sao bernardo do campo', 'campinas', 'caxias do sul', 'cascavel',
###    'niteroi', 'duque de caxias', 'londrina', 'nova iguacu', 'maringa',
###    'contagem', 'santo andre', 'juiz de fora', 'ponta grossa',
###    'pelotas', 'santa maria', 'canoas', 'uberaba'], dtype=object)
df["is_unknown"] = (df["city"] == "unknown").astype(int)
df["is_uberlandia"] = (df["city"] == "uberlandia").astype(int)
df["is_guarulhos"] = (df["city"] == "guarulhos").astype(int)
df["is_sao_paulo"] = (df["city"] == "sao paulo").astype(int)
df["is_sao_goncalo"] = (df["city"] == "sao goncalo").astype(int)
df["is_belo_horizonte"] = (df["city"] == "belo horizonte").astype(int)
df["is_curitiba"] = (df["city"] == "curitiba").astype(int)
df["is_porto_alegre"] = (df["city"] == "porto alegre").astype(int)
df["is_rio_de_janeiro"] = (df["city"] == "rio de janeiro").astype(int)
df["is_sao_bernardo_do_campo"] = (df["city"] == "sao bernardo do campo").astype(int)
df["is_campinas"] = (df["city"] == "campinas").astype(int)
df["is_caxias_do_sul"] = (df["city"] == "caxias do sul").astype(int)
df["is_cascavel"] = (df["city"] == "cascavel").astype(int)
df["is_niteroi"] = (df["city"] == "niteroi").astype(int)
df["is_duque_de_caxias"] = (df["city"] == "duque de caxias").astype(int)
df["is_londrina"] = (df["city"] == "londrina").astype(int)
df["is_nova_iguacu"] = (df["city"] == "nova iguacu").astype(int)
df["is_maringa"] = (df["city"] == "maringa").astype(int)
df["is_contagem"] = (df["city"] == "contagem").astype(int)
df["is_santo_andre"] = (df["city"] == "santo andre").astype(int)
df["is_juiz_de_fora"] = (df["city"] == "juiz de fora").astype(int)
df["is_ponta_grossa"] = (df["city"] == "ponta grossa").astype(int)
df["is_pelotas"] = (df["city"] == "pelotas").astype(int)
df["is_santa_maria"] = (df["city"] == "santa maria").astype(int)
df["is_canoas"] = (df["city"] == "canoas").astype(int)
df["is_uberaba"] = (df["city"] == "uberaba").astype(int)

###State: array(['SP', 'RJ', 'MG', 'RS', 'PR'], dtype=object)
df["is_SP"] = (df["state"] == "SP").astype(int)
df["is_RJ"] = (df["state"] == "RJ").astype(int)
df["is_MG"] = (df["state"] == "MG").astype(int)
df["is_RS"] = (df["state"] == "RS").astype(int)
df["is_PR"] = (df["state"] == "PR").astype(int)

###Category: array(['health', 'technology', 'fashion', 'toys', 'sports'], dtype=object)
df["is_health"] = (df["category"] == "health").astype(int)
df["is_technology"] = (df["category"] == "technology").astype(int)
df["is_fashion"] = (df["category"] == "fashion").astype(int)
df["is_toys"] = (df["category"] == "toys").astype(int)
df["is_sports"] = (df["category"] == "sports").astype(int)

###Prices:
df["total_price"] = df["price"] + df["shipping"]

std_scaler = StandardScaler()
df["price_scaled"] = std_scaler.fit_transform(df[["price"]])
df["shipping_scaled"] = std_scaler.fit_transform(df[["shipping"]])
df["total_price_scaled"] = std_scaler.fit_transform(df[["total_price"]])

df["price_shipping_rate"] = df["price"] / df["total_price"]
df["expensive_shipping"] = (df["shipping_scaled"] > 0).astype(int)

###Payment: array(['credit card', 'other'], dtype=object)
df["is_credit_card"] = (df["payment"] == "credit card").astype(int)

###Fechas:
df["int_dtpurchased"] = np.int64(df["purchased"])
df["int_dtdelivered"] = np.int64(df["delivered"])
df["int_dtestimated_delivery"] = np.int64(df["estimated_delivery"])

###Rating:
df["std_rating"] = np.int64(df["rating"]*2)

df.head(3)

"""Debido a que estaremos realizando clasificación, pasaremos `rating`de numérico a categórico. Deberás modificar `RATING_BINS`
y `RATING_LABELS` para seleccionar cómo realizar el *binning* de esta clase.

**Ejemplo:**
```python
    RATING_BINS = [0, 2, 3.5, 5]
    RATING_LABELS = ['low', 'medium', 'high']
```
"""

# Modifica RATING_BINS y RATING_LABELS según consideres.
RATING_BINS = [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]
RATING_LABELS = ['extreme low', 'very low', 'low', 'low medium', 'medium', 'high medium', 'high', 'very high', 'extreme high']

################################################################################

# ¡No modificar! Este código se encarga de crear la columna rating_class.
df['rating_class'] = pd.cut(df['rating'], bins=RATING_BINS, labels=RATING_LABELS, include_lowest=True)
df.value_counts(['rating', 'rating_class'], normalize=True, sort=False, dropna=False)

"""**¡Ten cuidado!** Debes intentar que tus `rating_class` no sean demasiado imbalancedas. Por ejemplo, que el 90% de los datos
sean *low*, 5% *medium* y 5% *high*. Es preferible algo como: 40% *low*, 30% *medium* y 30% *high*.
"""

# ¡No modificar!
df.value_counts('rating_class', normalize=True, sort=False, dropna=False)

"""# 2. ¡Wow! Gran *feature engineering*. Toca armar tu set para entrenar el modelo. ¿Podrías generar gráficas para el equipo de Customer Experience que expliquen mejor los datos nuevos? ¡No olvides explicarlas!

⁉️ **Consideración:** Modifica la lista de columnas a eliminar para el *train*. Debes de hacer por lo menos dos gráficos.

ℹ️ **HINT 1:** ¿Por qué tus gráficas aportan al equipo de Customer Experience? ¡Explica tus nuevas columnas! ¿No tienes? 😓

ℹ️ **HINT 2:** Un buen gráfico tiene título, *labels*, leyenda... ¡y mucho más!

📖 **Referencia Externa:** [Tutorial de Seaborn](https://www.datacamp.com/tutorial/seaborn-python-tutorial).

---

✅ **Explicación:**

- **Gráfico 1 (Gráfico de barras):** Un gráfico de barra se utiliza para mostrar la frecuencia o proporción de datos categóricos. Muestra los datos como barras rectangulares, donde la longitud de cada barra representa el valor de una categoría. Los gráficos de barras son los más adecuados para visualizar datos categóricos discretos **(Fuente: Visualización de datos Hecho Fácil, "Seaborn with Python: A Beginner’s Guide")**.

- **Gráfico 2 (Gráfico de dispersión):** Se utiliza un gráfico de dispersión para mostrar la conexión entre dos variables. Muestra un conjunto de puntos de datos, donde cada punto representa el valor de dos variables. Los gráficos de dispersión se utilizan con frecuencia para visualizar patrones y correlaciones en los datos. Son los más adecuados para los datos numéricos continuos **(Fuente: Visualización de datos Hecho Fácil, "Seaborn with Python: A Beginner’s Guide")**.
"""

# Gráfico 1: GRÁFICO DE BARRAS DE ÓRDENES PROCESADAS SEGÚN FORMA DE PAGO (1=TARJETA DE CRÉDITO, 0=OTRA)

########################################################################################################################

# Filtrar los datos para incluir únicamente a los sobrevivientes:
lproductosvendidos = df["is_credit_card"].value_counts() #Lista de ordenes agrupadas segun forma de pago
# Crear un grafico de barra usando Seaborn:
sns.barplot(x=lproductosvendidos.index, y=lproductosvendidos.values)
# Establezca el título de la trama y etiquetas de eje:
plt.title("Ordenes procesadas")
plt.xlabel("Formas de pago")
plt.ylabel("Cantidad")
# Guardar figura:
plt.savefig("bar-plot.png")
# Mostrar la trama:
plt.show()

# Gráfico 2: GRÁFICO DE DISPERSIÓN DE LAS ÓRDENES VERSUS EL N° ASOCIADO A LA FECHA DE ENTREGA.

########################################################################################################################

# Crear una "parcela" de dispersión usando Seaborn:
sns.scatterplot(x="order", y="int_dtdelivered", data=df) #Relacion entre las ordenes y la fecha de entrega
# Guardar figura:
plt.savefig("scatterplot.png")
# Mostrar la trama:
plt.show()

df.head(3)

# Modifica la lista de columnas a eliminar según consideres.

x = df.drop(
    columns=[
        # Agrega las columnas que consideres
        'order', 'product', 'seller', 'customer',
        'city', 'state', 'category', 'price', 'total_price','shipping', 'payment', 'purchased', 'delivered', 'estimated_delivery',
        'rating', 'rating_class'
    ]
)
print ("X es:")
x.head(1)
########################################################################################################################

# ¡No modificar! Esta celda se encarga de dividir los datos en conjuntos de entrenamiento, validación y prueba.
"""
y = df['rating_class']

x_train_val, x_test, y_train_val, y_test = train_test_split(x, y, test_size=0.2, shuffle=True, random_state=RANDOM_STATE)
x_train, x_val, y_train, y_val = train_test_split(x_train_val, y_train_val, test_size=0.2, shuffle=True, random_state=RANDOM_STATE)

print(f'Train: {x_train.shape[0]} rows')
print(f'Validation: {x_val.shape[0]} rows')
print(f'Test: {x_test.shape[0]} rows')

#x_train.head(5)
"""
