# -*- coding: utf-8 -*-
"""MP1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qcyKzQf9AoxVMfnHzOELvb2df-S4C3zw

# Miniproyecto 1: ¡Bienvenido a tu nueva empresa!
#### **Curso:** Introducción a Minería de Datos y Machine Learning

---

**¡Bienvenido a AMAZOFF!**

Has sido seleccionado para unirte al equipo de E-commerce como Data Scientist Junior.

Después de integrarte al equipo, te han asignado tu primera misión:

> Trabajar con una base de datos antigua y descuidada que durante años nadie ha limpiado ni analizado.

Tu tarea es realizar un preprocessing de alta calidad para convertir estos datos en información valiosa que respalde
decisiones estratégicas.

La base de datos contiene información crucial sobre clientes, productos y transacciones, pero está plagada de
inconsistencias, datos faltantes y otros problemas que dificultan su uso.

El reto es mayor porque los resultados de tu análisis y las respuestas a las preguntas de negocio serán presentados
directamente al CEO de AMAZOFF.

Por lo tanto, debes aplicar tus conocimientos técnicos y comprender cómo tus hallazgos se alinean con las necesidades y
objetivos de la empresa.

**¿Estás listo para asumir tu nueva misión y demostrar que puedes hacer la diferencia en AMAZOFF?**

¡Es hora de empezar y transformar esos datos en información estratégica para el negocio!

# Pauta de Evaluación

Este MP1 está enfocado en responder preguntas de negocio relevantes para **AMAZOFF**.

### Preguntas de Negocio

1. (20 puntos) Tu líder de equipo necesitará explicar qué información contiene la base de datos al CEO de la empresa. ¿Podrías explicarle qué información contienen los datos?
2. (15 puntos) ¡Habemus data! Me dicen que los datos estaban muy sucios... ¿podrías corregir esto?
3. (20 puntos) ¡Me encantan los datos limpios! Pero es mucha data. ¿Podrías hacer algunos gráficos interesantes para el equipo de Marketing?
4. (20 puntos) Marketing ama los gráficos. Pero el CEO es una persona de números. Te pide un informe con 3 estadísticas MUY interesantes y NUEVAS de los datos.
5. (10 puntos) [ ERROR ] Detectamos que el rating va de 1-5, pero nuestros sistemas solo toleran ratings normalizados. ¿Nos puedes ayudar?
6. (15 puntos) El CEO está interesado en simplificar el análisis de datos complejos sin perder información crucial. ¿Puedes aplicar una técnica de reducción de dimensionalidad como PCA y explicar los resultados?

### Tener en consideración:

En caso de que el código esté bien, pero no se responda (usando celdas de texto) la pregunta de negocio (sección **Explicación**), **se asignará máximo la mitad de puntos** de esa pregunta.

> Al principio de la pregunta 3 tendrás la opción de descomentar un código (dando una explicación) que te permitirá utilizar la base de datos `output.csv` como `df`. Esto, en caso de que la pregunta 2 la encuentres muy difícil. Sin embargo, esto automáticamente te pondrá 0 puntos en la pregunta 2. Sin dar una explicación de por qué utilizarás esta opción, el tutor corrector puede comentar nuevamente la celda y queda `df` según lo realizado en la pregunta 2. ¡Ten cuidado!

El miniproyecto está diseñado para completar código. Suba el notebook solo con el código para responder la pregunta de negocio.

> # ¡NO OLVIDES GUARDAR Y SUBIR EL NOTEBOOK A LA PLATAFORMA CUANDO TERMINES! FORMATO .ipynb

# Preámbulo
"""

# Machine Learning
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.decomposition import PCA

# General Data Science
from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# Esta configuración permite que los dataframes se muestren completos.
pd.set_option('display.max_columns', None)

"""[ AGREGA TU RESPUESTA ACÁ ]
"""

order = pd.read_csv('raw_ecommerce_order.csv', index_col=0, sep=',')# [ AGREGA TU CÓDIGO AQUÍ ]
order.head(2)

product = pd.read_csv('raw_ecommerce_product.csv', index_col=0, sep=',')# [ AGREGA TU CÓDIGO AQUÍ ]
product.head(2)

delivery = pd.read_csv('raw_ecommerce_delivery.csv', index_col=0, sep=',')# [ AGREGA TU CÓDIGO AQUÍ ]
delivery.head(2)

df = order.join(product.set_index("order"), on="order", rsuffix="_prodyct")
df = df.join(delivery.set_index("order"), on="order", rsuffix="_delivery")
df.head(3)

df.info()
