# -*- coding: utf-8 -*-
"""MP2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HTy6exDtCcrQxPJDrKNR89r5_NLY8Y-Q

# Miniproyecto 2: Machine Learning con Valor
#### **Curso:** Introducción a Minería de Datos y Machine Learning

---

**¡Felicidades por tu excelente trabajo en el MP1!**

Tu labor en el preprocesamiento de la base de datos ha causado un gran impacto en **AMAZOFF**.

El equipo de Customer Experience ha quedado impresionado con tu habilidad para transformar datos sucios en información
útil y ahora quieren aprovechar tus talentos para enfrentar un nuevo desafío.

Nos han pedido desarrollar un **Predictor de Ratings de Pedidos** utilizando los datos preprocesados de ratings de
pedidos de nuestra plataforma de e-commerce.
"""

from google.colab import drive
drive.mount('/content/drive')

"""# Pauta de Evaluación

Este MP2 está enfocado en responder preguntas de negocio relevantes para **AMAZOFF**.

### Preguntas de Negocio

1. (15 puntos) El equipo necesita extraer la máxima información de los datos. ¿Cómo modificarías la base de datos para ser usada con modelos de ML?
2. (15 puntos) ¡Wow! Gran *feature engineering*. Toca armar tu set para entrenar el modelo. ¿Podrías generar gráficas para el equipo de Customer Experience que expliquen mejor los datos nuevos? ¡No olvides explicarlas!
3. (10 puntos) Dicen que se pueden encontrar patrones en tus datos de entrenamiento. ¿Qué patrones encuentras en los pedidos? ¿Cómo pueden ser de utilidad para mejorar las ventas de AMAZOFF?
4. (25 puntos) ¡Viva el ML! Toca predecir la satisfacción del cliente. ¿Es posible predecir bien el `rating_class`?
5. (20 puntos) El equipo de Customer Experience dice que un solo modelo no es suficiente. ¿Podrías implementar otro?
6. (15 puntos) ¡Dos modelos! Eso es genial. ¿Qué modelo funcionó peor? ¿Si utilizas PCA podría mejor?

### Tener en consideración:

En caso de que el código esté bien, pero no se responda (usando celdas de texto) la pregunta de negocio (sección **Explicación**), **se asignará máximo la mitad de puntos** de esa pregunta.

El miniproyecto está diseñado para completar código. Suba el notebook solo con el código para responder la pregunta de negocio.

> # ¡NO OLVIDES GUARDAR Y SUBIR EL NOTEBOOK A LA PLATAFORMA CUANDO TERMINES! FORMATO .ipynb

# Preámbulo

**¡Cuidado!** En esta sección solo puedes modificar la sección de PÁRAMETROS.
"""

# ¡No modificar esta celda! No está permitido usar librerías adicionales.

# Association Rules
from mlxtend.frequent_patterns import apriori, association_rules

# Machine Learning
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA

# General Data Science
from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# Esta configuración permite que los dataframes se muestren completos.
pd.set_option('display.max_columns', None)

# PARÁMETROS (puedes modificar esta sección)

DATA_PATH = '/content/drive/MyDrive/Colab Notebooks/ecommerce.csv' # Si tienes el archivo en otro lugar, cámbialo.
RANDOM_STATE = 0 # ¡Cámbialo a tu número favorito!

# ¡No modificar! Esta celda se encarga de cargar los datos.
df = pd.read_csv(DATA_PATH)
df.purchased = pd.to_datetime(df.purchased)
df.delivered = pd.to_datetime(df.delivered)
df.estimated_delivery = pd.to_datetime(df.estimated_delivery)
print(f'{df.shape[0]} rows x {df.shape[1]} columns')
df.head(5)

# ¿Cuántos valores únicos hay en cada columna?
for col in df.columns:
    print(f'{col}: {df[col].nunique()} unique values')

df.dtypes

df.city.unique()

df.state.unique()

df.category.unique()

df.payment.unique()

print (f"{np.min(df.purchased)} - {np.max(df.purchased)}")

print (f"{np.min(df.delivered)} - {np.max(df.delivered)}")

print (f"{np.min(df.estimated_delivery)} - {np.max(df.estimated_delivery)}")

df.rating.unique()

"""# 1. El equipo necesita extraer la máxima información de los datos. ¿Cómo modificarías la base de datos para ser usada con modelos de ML?

⁉️ **Consideración:** La última celda de esta sección es la de cálculo de `rating_class`, mantener el orden. Agregar las celdas para modificar
los datos, antes de esta. No olvides modificar el código para calcular la clase de rating.

ℹ️ **HINT:** Utiliza una celda para cada columna. ¿Qué columnas no sirven? ¿Qué columnas necesito que sean números? ¿Nuevas columnas?

📖 **Referencia Externa:** [Feature Engineering](https://www.freecodecamp.org/news/feature-engineering-techniques-for-structured-data/).

---

✅ **Explicación:**

Se lleva a cabo una transformación de datos, desde una forma no numérica a numérica, esto es, a valores enteros. Tales nuevos valores facilitarán el entrenamiento para el aprendizaje automático, que permitirá a la máquina hacer una mejor clasificación a la hora de hacer, por parte de ésta, una predicción sobre los datos que se le suministren. Para hacer esta transformación se aplica un criterio binario 0 ó 1, para la mayoría de las características, para indicar la presencia (1) o ausencia (0) de una determinada feature. Se aplica este criterio dada la imposibilidad de establecer un valor cuantificable que indique la distancia entre dos o más características de tipo string. Distinto es el caso de las fechas, en el que se toma como valor numérico, los nanosegundos correspondientes a cada una.
"""

###City: array(['unknown', 'uberlandia', 'guarulhos', 'sao paulo', 'sao goncalo',
###    'belo horizonte', 'curitiba', 'porto alegre', 'rio de janeiro',
###    'sao bernardo do campo', 'campinas', 'caxias do sul', 'cascavel',
###    'niteroi', 'duque de caxias', 'londrina', 'nova iguacu', 'maringa',
###    'contagem', 'santo andre', 'juiz de fora', 'ponta grossa',
###    'pelotas', 'santa maria', 'canoas', 'uberaba'], dtype=object)
df["is_unknown"] = (df["city"] == "unknown").astype(int)
df["is_uberlandia"] = (df["city"] == "uberlandia").astype(int)
df["is_guarulhos"] = (df["city"] == "guarulhos").astype(int)
df["is_sao_paulo"] = (df["city"] == "sao paulo").astype(int)
df["is_sao_goncalo"] = (df["city"] == "sao goncalo").astype(int)
df["is_belo_horizonte"] = (df["city"] == "belo horizonte").astype(int)
df["is_curitiba"] = (df["city"] == "curitiba").astype(int)
df["is_porto_alegre"] = (df["city"] == "porto alegre").astype(int)
df["is_rio_de_janeiro"] = (df["city"] == "rio de janeiro").astype(int)
df["is_sao_bernardo_do_campo"] = (df["city"] == "sao bernardo do campo").astype(int)
df["is_campinas"] = (df["city"] == "campinas").astype(int)
df["is_caxias_do_sul"] = (df["city"] == "caxias do sul").astype(int)
df["is_cascavel"] = (df["city"] == "cascavel").astype(int)
df["is_niteroi"] = (df["city"] == "niteroi").astype(int)
df["is_duque_de_caxias"] = (df["city"] == "duque de caxias").astype(int)
df["is_londrina"] = (df["city"] == "londrina").astype(int)
df["is_nova_iguacu"] = (df["city"] == "nova iguacu").astype(int)
df["is_maringa"] = (df["city"] == "maringa").astype(int)
df["is_contagem"] = (df["city"] == "contagem").astype(int)
df["is_santo_andre"] = (df["city"] == "santo andre").astype(int)
df["is_juiz_de_fora"] = (df["city"] == "juiz de fora").astype(int)
df["is_ponta_grossa"] = (df["city"] == "ponta grossa").astype(int)
df["is_pelotas"] = (df["city"] == "pelotas").astype(int)
df["is_santa_maria"] = (df["city"] == "santa maria").astype(int)
df["is_canoas"] = (df["city"] == "canoas").astype(int)
df["is_uberaba"] = (df["city"] == "uberaba").astype(int)

###State: array(['SP', 'RJ', 'MG', 'RS', 'PR'], dtype=object)
df["is_SP"] = (df["state"] == "SP").astype(int)
df["is_RJ"] = (df["state"] == "RJ").astype(int)
df["is_MG"] = (df["state"] == "MG").astype(int)
df["is_RS"] = (df["state"] == "RS").astype(int)
df["is_PR"] = (df["state"] == "PR").astype(int)

###Category: array(['health', 'technology', 'fashion', 'toys', 'sports'], dtype=object)
df["is_health"] = (df["category"] == "health").astype(int)
df["is_technology"] = (df["category"] == "technology").astype(int)
df["is_fashion"] = (df["category"] == "fashion").astype(int)
df["is_toys"] = (df["category"] == "toys").astype(int)
df["is_sports"] = (df["category"] == "sports").astype(int)

###Prices:
df["total_price"] = df["price"] + df["shipping"]

std_scaler = StandardScaler()
df["price_scaled"] = std_scaler.fit_transform(df[["price"]])
df["shipping_scaled"] = std_scaler.fit_transform(df[["shipping"]])
df["total_price_scaled"] = std_scaler.fit_transform(df[["total_price"]])

df["price_shipping_rate"] = df["price"] / df["total_price"]
df["expensive_shipping"] = (df["shipping_scaled"] > 0).astype(int)

###Payment: array(['credit card', 'other'], dtype=object)
df["is_credit_card"] = (df["payment"] == "credit card").astype(int)

###Fechas:
df["int_dtpurchased"] = np.int64(df["purchased"])
df["int_dtdelivered"] = np.int64(df["delivered"])
df["int_dtestimated_delivery"] = np.int64(df["estimated_delivery"])

###Rating:
df["std_rating"] = np.int64(df["rating"]*2)

df.head(3)

"""Debido a que estaremos realizando clasificación, pasaremos `rating`de numérico a categórico. Deberás modificar `RATING_BINS`
y `RATING_LABELS` para seleccionar cómo realizar el *binning* de esta clase.

**Ejemplo:**
```python
    RATING_BINS = [0, 2, 3.5, 5]
    RATING_LABELS = ['low', 'medium', 'high']
```
"""

# Modifica RATING_BINS y RATING_LABELS según consideres.
RATING_BINS = [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]
RATING_LABELS = ['extreme low', 'very low', 'low', 'low medium', 'medium', 'high medium', 'high', 'very high', 'extreme high']

################################################################################

# ¡No modificar! Este código se encarga de crear la columna rating_class.
df['rating_class'] = pd.cut(df['rating'], bins=RATING_BINS, labels=RATING_LABELS, include_lowest=True)
df.value_counts(['rating', 'rating_class'], normalize=True, sort=False, dropna=False)

"""**¡Ten cuidado!** Debes intentar que tus `rating_class` no sean demasiado imbalancedas. Por ejemplo, que el 90% de los datos
sean *low*, 5% *medium* y 5% *high*. Es preferible algo como: 40% *low*, 30% *medium* y 30% *high*.
"""

# ¡No modificar!
df.value_counts('rating_class', normalize=True, sort=False, dropna=False)

"""# 2. ¡Wow! Gran *feature engineering*. Toca armar tu set para entrenar el modelo. ¿Podrías generar gráficas para el equipo de Customer Experience que expliquen mejor los datos nuevos? ¡No olvides explicarlas!

⁉️ **Consideración:** Modifica la lista de columnas a eliminar para el *train*. Debes de hacer por lo menos dos gráficos.

ℹ️ **HINT 1:** ¿Por qué tus gráficas aportan al equipo de Customer Experience? ¡Explica tus nuevas columnas! ¿No tienes? 😓

ℹ️ **HINT 2:** Un buen gráfico tiene título, *labels*, leyenda... ¡y mucho más!

📖 **Referencia Externa:** [Tutorial de Seaborn](https://www.datacamp.com/tutorial/seaborn-python-tutorial).

---

✅ **Explicación:**

- **Gráfico 1 (Gráfico de barras):** Un gráfico de barra se utiliza para mostrar la frecuencia o proporción de datos categóricos. Muestra los datos como barras rectangulares, donde la longitud de cada barra representa el valor de una categoría. Los gráficos de barras son los más adecuados para visualizar datos categóricos discretos **(Fuente: Visualización de datos Hecho Fácil, "Seaborn with Python: A Beginner’s Guide")**.

- **Gráfico 2 (Gráfico de dispersión):** Se utiliza un gráfico de dispersión para mostrar la conexión entre dos variables. Muestra un conjunto de puntos de datos, donde cada punto representa el valor de dos variables. Los gráficos de dispersión se utilizan con frecuencia para visualizar patrones y correlaciones en los datos. Son los más adecuados para los datos numéricos continuos **(Fuente: Visualización de datos Hecho Fácil, "Seaborn with Python: A Beginner’s Guide")**.
"""

# Gráfico 1: GRÁFICO DE BARRAS DE ÓRDENES PROCESADAS SEGÚN FORMA DE PAGO (1=TARJETA DE CRÉDITO, 0=OTRA)

########################################################################################################################

# Filtrar los datos para incluir únicamente a los sobrevivientes:
lproductosvendidos = df["is_credit_card"].value_counts() #Lista de ordenes agrupadas segun forma de pago
# Crear un grafico de barra usando Seaborn:
sns.barplot(x=lproductosvendidos.index, y=lproductosvendidos.values)
# Establezca el título de la trama y etiquetas de eje:
plt.title("Ordenes procesadas")
plt.xlabel("Formas de pago")
plt.ylabel("Cantidad")
# Guardar figura:
plt.savefig("/content/drive/MyDrive/Colab Notebooks/bar-plot.png")
# Mostrar la trama:
plt.show()

# Gráfico 2: GRÁFICO DE DISPERSIÓN DE LAS ÓRDENES VERSUS EL N° ASOCIADO A LA FECHA DE ENTREGA.

########################################################################################################################

# Crear una "parcela" de dispersión usando Seaborn:
sns.scatterplot(x="order", y="int_dtdelivered", data=df) #Relacion entre las ordenes y la fecha de entrega
# Guardar figura:
plt.savefig("/content/drive/MyDrive/Colab Notebooks/scatterplot.png")
# Mostrar la trama:
plt.show()

df.head(3)

# Modifica la lista de columnas a eliminar según consideres.

x = df.drop(
    columns=[
        # Agrega las columnas que consideres
        'order', 'product', 'seller', 'customer',
        'city', 'state', 'category', 'price', 'total_price','shipping', 'payment', 'purchased', 'delivered', 'estimated_delivery',
        'rating', 'rating_class'
    ]
)

########################################################################################################################

# ¡No modificar! Esta celda se encarga de dividir los datos en conjuntos de entrenamiento, validación y prueba.

y = df['rating_class']

x_train_val, x_test, y_train_val, y_test = train_test_split(x, y, test_size=0.2, shuffle=True, random_state=RANDOM_STATE)
x_train, x_val, y_train, y_val = train_test_split(x_train_val, y_train_val, test_size=0.2, shuffle=True, random_state=RANDOM_STATE)

print(f'Train: {x_train.shape[0]} rows')
print(f'Validation: {x_val.shape[0]} rows')
print(f'Test: {x_test.shape[0]} rows')

display(x_train.head(5))

display(y_train.head(5))

"""# 3. Dicen que se pueden encontrar patrones en tus datos de entrenamiento. ¿Qué patrones encuentras en los pedidos? ¿Cómo pueden ser de utilidad para mejorar las ventas de AMAZOFF?

⁉️ **Consideración:** Utiliza reglas de asociación para encontrar reglas útiles para nuevas estrategias de venta. Explica los parámetros y métricas de tu modelo.

ℹ️ **HINT 1:** ¿Qué librería se importó en el inicio? Cuidado, ¡solo datos binarios!

ℹ️ **HINT 2:** De las principales reglas encontradas... ¿cómo implementarías una estrategia de venta/marketing utilizando esta información?

📖 **Referencia Externa:** [Documentación de mlxtend](https://rasbt.github.io/mlxtend/user_guide/frequent_patterns/apriori/).

---

✅ **Explicación:**

Para hallar reglas de asociación se utiliza el algoritmo Apriori. En primer lugar se ocupa un dataframe que no incluya las columnas no binarias de la forma 0 ó 1, transformándolas posteriormente a su valor booleano respectivo, requerido por el método apriori() de la librería mlxtend. Se ocupa un umbral de 0.5 para efectos de discriminar sólo aquellas reglas que cumplan con dicha frecuencia relativa (soporte) mínima. Finalmente se muestran las transacciones que cumplan con dichas reglas encontradas.
"""

binary_x_train = x_train.drop(
    columns=[
        # Agrega las columnas que consideres
        'int_dtpurchased', 'int_dtdelivered', 'int_dtestimated_delivery',
        'price_scaled', 'shipping_scaled', 'total_price_scaled', 'price_shipping_rate', 'std_rating'
    ]
).astype(bool)

frequent_itemsets = apriori(binary_x_train, min_support=0.5, use_colnames=True) #Definimos un umbral de 1/2
frequent_itemsets

rules = df[df["is_unknown"]==1][df["is_SP"]==1][df["is_credit_card"]==1]
rules

"""# 4. ¡Viva el ML! Toca predecir la satisfacción del cliente. ¿Es posible predecir bien el `rating_class`?

⁉️ **Consideraciones:**

- Elige tres sets de hiperparámetros **diferentes** para los tres modelos de clasificación de *Random Forest*.
- Debes modificar al menos 4 hiperparámetros. No cuentes `random_state`ni `n_jobs`.
- Tus sets de hiperparámetros deben pasar la prueba de *overfitting* y *underfitting*.
- Utiliza los resultados de la validación para elegir tus hiperparámetros, no los del testeo.
- No olvides interpretar tus resultados e intenta relacionarlos a los intereses de **AMAZOFF** si es posible.

ℹ️ **HINT:** El ML es un proceso iterativo, a veces si es que no funcionan bien tus resultados debes de volver a empezar.

📖 **Referencia Externa:** [RandomForestClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html).

---

✅ **Explicación:**

- **Justifica tus hiperpámetros:** Se ocupan los parámetros n_estimators (número de árboles), max_depth (profundidad del árbol), max_features (número de características a considerar para buscar la mejor división) y criterion (función para medir la calidad de una división, que puede ser Gini, Entropy o LogLoss). Se utilizan diferentes combinaciones de estos parámetros para cada uno de los tres bosques aleatorios, con el fin de medir cual de ellos es el de mayor rendimiento.
- **¿Hay *overfitting* o *underfitting*:** Los parámetros evaluados muestran un infraajuste (underfitting) en el caso del primero y el último de los bosques aleatorios utilizados, que demostraron tener un menor rendimiento en comparación con el segundo bosque aleatorio que fue el de mayor exactitud, aunque fue también el de mayor tiempo de ejecución con 50.9 segundos en Google Colabs.
- **Resultados de Validación:** El segundo bosque aleatorio mostró una mayor exactitud (accuracy) con 0.95 versus 0.58 y 0.91 del primer y último bosque respectivamente.
- **Resultados de Testeo:** Con los datos de testeo los bosques alatorios obtuvieron una axactitud predictiva de 0.57, 0.95 y 0.91 respectivamente.
- **¿Es posible predecir bien el `rating_class`:** Con los datos suministrados se observó un buen nivel predictivo, con 0.95 de exactitud para el segundo bosque aleatorio evaluado.
"""

x_train.head(1)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# # Debes de modificar al menos 4 parámetros, sin contar random_state y n_jobs.
# 
# rf1 = RandomForestClassifier(
#     n_estimators=200,           #Num. arboles, 100 por defecto
#     max_depth=5,                #Profundidad del arbol
#     max_features=3,             #Num. maximo de caracteristicas a considerar
#     criterion="entropy",        #Criterio Entropia, por defecto: Gini
#     random_state=RANDOM_STATE,
#     n_jobs=-1
# )
# 
# rf1.fit(x_train, y_train)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# # Debes de modificar al menos 4 parámetros, sin contar random_state y n_jobs.
# 
# rf2 = RandomForestClassifier(
#     n_estimators=500,           #Num. arboles, 100 por defecto
#     max_depth=10,               #Profundidad del arbol
#     max_features=6,             #Num. maximo de caracteristicas a considerar
#     criterion="log_loss",       #Criterio Log Loss, por defecto: Gini
#     random_state=RANDOM_STATE,
#     n_jobs=-1
# )
# 
# rf2.fit(x_train, y_train)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# # Debes de modificar al menos 4 parámetros, sin contar random_state y n_jobs.
# 
# rf3 = RandomForestClassifier(
#     n_estimators=400,           #Num. arboles, 100 por defecto
#     max_depth=8,                #Profundidad del arbol
#     max_features=6,             #Num. maximo de caracteristicas a considerar
#     criterion="entropy",        #Criterio Entropia, por defecto: Gini
#     random_state=RANDOM_STATE,
#     n_jobs=-1
# )
# 
# rf3.fit(x_train, y_train)

# ¡No modificar! Esta celda se encarga de evaluar los modelos y mostrar los resultados.

y_val_pred1 = rf1.predict(x_val)
y_val_pred2 = rf2.predict(x_val)
y_val_pred3 = rf3.predict(x_val)

print('[Random Forest] Check Overfitting with Accuracy')
print(f'RF1: train={accuracy_score(y_train, rf1.predict(x_train)):.4f} val={accuracy_score(y_val, y_val_pred1):.4f}')
print(f'RF2: train={accuracy_score(y_train, rf2.predict(x_train)):.4f} val={accuracy_score(y_val, y_val_pred2):.4f}')
print(f'RF3: train={accuracy_score(y_train, rf3.predict(x_train)):.4f} val={accuracy_score(y_val, y_val_pred3):.4f}')

# ¡No modificar! Esta celda se encarga de mostrar los resultados en el set de validación.

print('[Random Forest] Validation Classification Report')
print('#'*80)
print('RF1')
print(classification_report(y_val, y_val_pred1))
print('#'*80)
print('RF2')
print(classification_report(y_val, y_val_pred2))
print('#'*80)
print('RF3')
print(classification_report(y_val, y_val_pred3))

# ¡Completa el código! Esta celda se encarga de evaluar los modelos en el set de testeo y mostrar los resultados.

y_pred_rf1 = rf1.predict(x_test)
y_pred_rf2 = rf2.predict(x_test)
y_pred_rf3 = rf3.predict(x_test)

print('[Random Forest] Test Classification Report')
print('#'*80)
print('RF1')
print(classification_report(y_test, y_pred_rf1))
print('#'*80)
print('RF2')
print(classification_report(y_test, y_pred_rf2))
print('#'*80)
print('RF3')
print(classification_report(y_test, y_pred_rf3))

"""# 5. El equipo de Customer Experience dice que un solo modelo no es suficiente. ¿Podrías implementar otro?

⁉️ **Consideración:** Utiliza otro modelo visto en clase, como *KNN* y repite todos los pasos de la pregunta 4. No utilices *Random Forest*.

ℹ️ **HINT 1:** No olvides elegir 3 set de hiperparámetros y analizar los resultados de validación y testeo.

ℹ️ **HINT 2:** Si utilizas un modelo no visto en clases, debes de explicar su funcionamiento para utilizarlo.

📖 **Referencia Externa:** [KNN](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html).

---

✅ **Explicación:** Se ocupa el algoritmo de KNN y se construyen 3 clasificadores con éste, variando sus parámetros de entrada.

- **Justifica tus hiperpámetros:** Se ocupan los parámetros de n_neighbors (num. de vecinos), weights (función de peso), algorithm (algoritmo a utilizar), leaf_size (tamaño de la hoja), n_jobs (num. de procesadores a ejecutar). Para efectos de las pruebas, se dejan fijos los 2 primeros, con los valores 30 y 'distance' respectivamente, y también los 2 últimos con los valores respectivos de 50 y -1 (todos los procesadores), y se varía el algoritmo a utilizar, ocupando BallTree, KDTree y fuerza bruta (Brute) en cada caso.
- **¿Hay *overfitting* o *underfitting*:** Se aprecia un subajuste (underfitting), dado el bajo rendimiento (precisión en torno al 30%) obtenido para los 3 clasificadores.
- **Resultados de Validación:** Se obtiene una precisión relativamente baja para los 3 clasificadores, con 0.31 para los 2 primeros y 0.3 para el último.
- **Resultados de Testeo:** Para el caso del testeo se obtiene una precisión de 0.3 para los 3 clasificadores.
- **¿Es posible predecir bien el `rating_class`:** El clasificador, con los parámetros evaluados, en general muestra una capacidad predictiva baja, de tan solo un 30%, para todas las combinaciones de parámetros evaluados.
"""

x_train.head(1)

y_train.head(5)

# Si usas un modelo no visto en clase: Descomenta e importa tu nuevo modelo de clasificación aquí.
# ¡No olvides agregar a tu explicación cómo funciona el modelo no visto en clase!

# from sklearn.

# Commented out IPython magic to ensure Python compatibility.
# # Instancia tu modelo 1 aquí.
# 
# %%time
# 
# # Clasificador KNN1:
# 
# kn1 = KNeighborsClassifier(
#     n_neighbors=30,             #Num. de vecinos, 5 por defecto
#     weights="distance",         #Funcion de peso (uniform ó distance), por defecto: Uniform
#     algorithm="ball_tree",      #Algoritmo a utilizar (auto, ball_tree, kd_tree, brute), por defecto Auto
#     leaf_size=50,               #Tamaño de la hoja que se pasa al algoritmo ball_tree o kd_tree, 30 por defecto
#     n_jobs=-1                   #Todos los procesadores (-1)
# )
# 
# kn1.fit(x_train, y_train)

# Commented out IPython magic to ensure Python compatibility.
# # Instancia tu modelo 2 aquí.
# 
# %%time
# 
# # Clasificador KNN2:
# 
# kn2 = KNeighborsClassifier(
#     n_neighbors=30,             #Num. de vecinos, 5 por defecto
#     weights="distance",         #Funcion de peso (uniform ó distance), por defecto: Uniform
#     algorithm="kd_tree",        #Algoritmo a utilizar (auto, ball_tree, kd_tree, brute), por defecto Auto
#     leaf_size=50,               #Tamaño de la hoja que se pasa al algoritmo ball_tree o kd_tree, 30 por defecto
#     n_jobs=-1                   #Todos los procesadores (-1)
# )
# 
# kn2.fit(x_train, y_train)

# Commented out IPython magic to ensure Python compatibility.
# # Instancia tu modelo 3 aquí.
# 
# %%time
# 
# # Clasificador KNN3:
# 
# kn3 = KNeighborsClassifier(
#     n_neighbors=30,             #Num. de vecinos, 5 por defecto
#     weights="distance",         #Funcion de peso (uniform ó distance), por defecto: Uniform
#     algorithm="brute",          #Algoritmo a utilizar (auto, ball_tree, kd_tree, brute), por defecto Auto
#     leaf_size=50,               #Tamaño de la hoja que se pasa al algoritmo ball_tree o kd_tree, 30 por defecto
#     n_jobs=-1                   #Todos los procesadores (-1)
# )
# 
# kn3.fit(x_train, y_train)

# Revisa si hay overfitting (resultado de entrenamiento muy superior al de validación).
# Utiliza: `accuracy_score`.

# Esta celda se encarga de evaluar los modelos y mostrar los resultados:

y_val_pred1 = kn1.predict(x_val)
y_val_pred2 = kn2.predict(x_val)
y_val_pred3 = kn3.predict(x_val)

print('[KNN] Check Overfitting with Accuracy')
print(f'KN1: train={accuracy_score(y_train, kn1.predict(x_train)):.4f} val={accuracy_score(y_val, y_val_pred1):.4f}')
print(f'KN2: train={accuracy_score(y_train, kn2.predict(x_train)):.4f} val={accuracy_score(y_val, y_val_pred2):.4f}')
print(f'KN3: train={accuracy_score(y_train, kn3.predict(x_train)):.4f} val={accuracy_score(y_val, y_val_pred3):.4f}')

# Imprime los resultados de tus modelos en el set de validación (classification_report).

# Esta celda se encarga de mostrar los resultados en el set de validación:

print('[KNN] Validation Classification Report')
print('#'*80)
print('KN1')
print(classification_report(y_val, y_val_pred1))
print('#'*80)
print('KN2')
print(classification_report(y_val, y_val_pred2))
print('#'*80)
print('KN3')
print(classification_report(y_val, y_val_pred3))

# Imprime los resultados de tus modelos en el set de testeo (classification_report).

# Esta celda se encarga de evaluar los modelos en el set de testeo y mostrar los resultados:

y_pred_kn1 = kn1.predict(x_test)
y_pred_kn2 = kn2.predict(x_test)
y_pred_kn3 = kn3.predict(x_test)

print('[KNN] Test Classification Report')
print('#'*80)
print('KN1')
print(classification_report(y_test, y_pred_kn1))
print('#'*80)
print('KN2')
print(classification_report(y_test, y_pred_kn2))
print('#'*80)
print('KN3')
print(classification_report(y_test, y_pred_kn3))

"""# 6. ¡Dos modelos! Eso es genial. ¿Qué modelo funcionó peor? ¿Si utilizas PCA podría mejor?

⁉️ **Consideración:** Elige la combinación de modelo e hiperparámetros que peor se desempeño entre las preguntas 4 y 5. Aplica PCA con un número de componentes adecuado y corre los resultados otra vez.

ℹ️ **HINT:** ¿Cómo se elige el número de componentes? ¿Y ese gráfico para qué sirve?

📖 **Referencia Externa:** [PCA](https://www.baeldung.com/cs/pca).

---

✅ **Explicación:** Se ocupa el Random Forest con los parámetros de mejor rendimiento obtenido para el algoritmo.

- **¿Por qué elegiste ese número de componentes?** Una reducción de dimensionalidad puede facilitar el análisis por parte del clasificador. Se prueba con 3 componentes principales.
- **Resultados de Validación:** Se obtiene una precisión baja, de tan solo un 27%.
- **Resultados de Testeo:** Se obtiene también una precisión baja, de un 28%.
- **¿Mejoraron los resultados al usar PCA? ¿Por qué?** Con la reducción de dimensionalidad se observa un empeoramiento de la calidad predictiva del clasificador para el caso visto. La totalidad de los componentes de los datos suministrados parace ser determinante para establecer las reglas de asociación correspondientes a un rating en particular.
"""

# ¡No modificar! Gráfico de Varianza Explicada por Número de Componentes

explained_variance = []
for i in range(1, 8):
    pca = PCA(n_components=i)
    pca.fit(x_train)
    explained_variance.append(pca.explained_variance_ratio_.sum())

plt.plot(range(1, 8), explained_variance, marker='o')
plt.xlabel('Number of Components')
plt.ylabel('Explained Variance')
plt.title('PCA Explained Variance')
plt.show()

# Elige el número de componentes que consideres adecuado.

pca = PCA(n_components=3) # modelo de PCA con 3 componentes

########################################################################################################################

# ¡No modificar! Esta celda se encarga de transformar los datos con PCA.

pca.fit(x_train)

x_train_pca = pca.transform(x_train)
x_val_pca = pca.transform(x_val)
x_test_pca = pca.transform(x_test)

# Elige el modelo que deseas utilizar. Selecciona los hiperparámetros que consideres. ¿Elegiste la peor combinación anterior?
#     Ejemplo 1: model = RandomForestClassifier(n_estimators=100, random_state=RANDOM_STATE).
#     Ejemplo 2: model = KNeighborsClassifier(n_neighbors=10).

model = RandomForestClassifier(
    n_estimators=500,           #Num. arboles, 100 por defecto
    max_depth=10,               #Profundidad del arbol
    max_features=6,             #Num. maximo de caracteristicas a considerar
    criterion="log_loss",       #Criterio Log Loss, por defecto: Gini
    random_state=RANDOM_STATE,
    n_jobs=-1
)

########################################################################################################################

# ¡No modificar! Este código se encarga de entrenar el modelo y mostrar los resultados en el set de validación.

model.fit(x_train_pca, y_train)

y_val_pca_pred = model.predict(x_val_pca)

print(f'[{model.__class__.__name__}] Validation Classification Report')
print(classification_report(y_val, y_val_pca_pred))

# ¡No modificar! Esta celda se encarga de mostrar los resultados en el set de test.

y_test_pca_pred = model.predict(x_test_pca)

print(f'[{model.__class__.__name__}] Test Classification Report')
print(classification_report(y_test, y_test_pca_pred))

"""> # ¡NO OLVIDES GUARDAR Y SUBIR EL NOTEBOOK A LA PLATAFORMA CUANDO TERMINES! FORMATO .ipynb"""