# -*- coding: utf-8 -*-
"""00_Ejemplos_adicionales_ggplot2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AfYDW06KwIe251Uo27McLpINd_m_na-U

<a href="https://colab.research.google.com/github/majorquev/DBDC_202507_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/Clase5/00_Ejemplos_adicionales_ggplot2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ejemplos adicionales ggplot2

**Autor:** Miguel Jorquera Viguera.<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales<br>
**E-mail ayudante:** rumorale1@gmail.com
"""

#install.packages("nycflights13")

library(ggplot2)
library(dplyr)
library(nycflights13)

"""## `stat_bin()`: Permite generar bines en la data y visualizar etiquetas entre otros elementos

1.- Creamos un histograma con 10 bins, y visualizaremos los conteos en etiquetas sobre cada barra del histograma. Para ello considerar a función `stat_bin` con parámetros `geom = 'label'`, y `mapping = aes(label=..count..)`.
"""

library(ggplot2)
library(dplyr)
# Histograma de frecuencias absolutas con R base.
set.seed(15)
data <- data.frame(x = rnorm(1000))
head(data)

hist(data$x, freq = F)# Freq = T (defecto) muestra histograma de frecuencias absolutas, mientras que freq = F, genera histograma de densidades.

"""2.- Misma Visualización pero con Ggplot2 y etiquetas con `stat_bin()` y `geom = label`"""

# ggplot2
# Histograma de frecuencias absolutas
data %>%
  ggplot() +
  aes(x = x) +
  geom_histogram(
    bins = 16,
    fill = "green",
    color = "red"
  ) +
  stat_bin(
    bins = 16,
    geom = "label",
    mapping = aes(label = after_stat(count))
  )

"""3.- Histograma de densidades, mismas visualizaciones.
 > Recordar: [Tipos de histogramas](https://math.stackexchange.com/questions/2666834/what-is-the-difference-between-frequency-and-density-in-a-histogram)


"""

data %>%
  ggplot() +
  aes(x = x, y = after_stat(density)) +
  geom_histogram(
    bins = 16,
    fill = "green",
    color = "red"
  ) +
  stat_bin(
    bins = 16,
    geom = "label",
    mapping = aes(label = round(after_stat(density), 2) )
  )

#"""## `theme()`: Permite modificar diversos parámetros gráficos, en particualar la orientación de los ejes.
#
#En este ejemplo consideraremos la data de vuelos, para lo cual buscaremos visualizar la serie que contiene el total de vuelos por cada día.
#Adicionalmente modificaremos la orientación de las etiquetas del eje X mediante la función `theme()`.
#"""

?theme

# Orientación etiquetas ejes ----------------------------------------------
data(flights)

# A modo de ejemplo podemos visulizar el total de vuelos por día .

# Primero podemos generar est resumen de vuelos en un df

head(flights)

resumen <- flights %>%
  mutate(fecha = as.Date(time_hour)) %>%
  count(fecha)

head(resumen)

resumen %>%
  filter(fecha <= "2013-12-31") %>%
  ggplot() +
  aes(x = fecha, y = n )+
  geom_line(col = "blue") +
  theme(panel.background = element_rect(fill = "red", color = "green") ,
        axis.text.x = element_text(angle = 45)) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %y")
# La función element_text() permite modificar orientación, y ajste vertical y hoizontal

"""## `geom_bar()`, `geom_label()`: Al igual que `geom_text()`, permite añadir etiquetas en la visualización, sin la necesidad de generar manualmente los bins.

 1. Construir un gráfico de barras con el total de vuelos por cada carrier.


"""

data(flights)

flights %>%
  ggplot() +
  aes(x = carrier) +
  geom_bar()

""" 2. Construir un gráfico de barras con el total de vuelos por cada carrier, pero considerando un dataframe con los conteos ya calculados.

"""

flights %>%
  count(carrier) %>%
  ggplot() +
  aes(x = carrier) +
  geom_bar()

g2 <- flights %>%
  count(carrier) %>%
  ggplot() +
  aes(x = carrier, y = n) +
  geom_bar(stat = "identity")

g2

"""3. Añada etiquetas con los totales de vuelos en cada barra"""

g2 +
  geom_label(mapping = aes(label = n), col = "red")

""" 4. Considere un gráfico de barras con los totales de vuelos por aeropuerto de destino, pero solo muestre aeropuertos de destino de ranking 1, 10 y 20 (según su cantidad de vuelos, donde 1 representa al aeropuerto de destino con mayor cantidad de vuelos)."""

flights %>%
  group_by(dest) %>%
  summarise(total_vuelos = n()) %>%
  mutate(rk2 = dense_rank(desc(total_vuelos) )) %>%
  arrange(desc(total_vuelos)) %>% # Opción 1
  mutate(rk = row_number()) %>%# Opción 1
  filter(rk %in% c(1,10,20)) %>%
  ggplot() +
  aes(x = dest, y = total_vuelos) +
  geom_bar(stat = "identity")

""" 5. Para los aeropuertos identificados en el punto dos, construir un gráfico de barras stackeado (stacked barchart) que muestre el total de vuelos por aeropuerto de origen."""

total_dest <- flights %>%
  count(dest, name = "total_dest") %>%
  arrange(desc(total_dest)) %>%
  mutate(rk = row_number())

# OP1
 aux <- flights %>%
  count(origin, dest, name = "total_orig_dest") %>%# filtrar donde dest in DCA, LAS y ORD NOOOO
  arrange(desc(dest)) %>%
  left_join(total_dest, by="dest") %>% # para entender que estamos distribuynto el total por destino en cada origen
  filter(rk %in% c(1,10,20))
aux

#OP2
aux2 <- flights %>%
  count(origin, dest, name = "total_orig_dest") %>%
  group_by(dest) %>%
  mutate(total_dest = sum(total_orig_dest)) %>%
  ungroup() %>% # Con esta funci{on le indicamos a R que no sonsidere los grupos definidos en group_by para las siguientes operaciones.
  mutate(rk = dense_rank(desc(total_dest))) %>%
  filter(rk %in% c(1,10,20)) %>%
  arrange(desc(total_dest))   # validar visualmente

aux2

aux %>%
  ggplot() +
  aes(x = dest, y = total_orig_dest, color = origin, fill = origin) +
  geom_bar(stat = "identity") + # por defecto viene el stacked bar plot
  geom_label(mapping = aes(label = total_orig_dest), position = position_stack(vjust = 0.5) , color = "black")

aux %>%
  ggplot() +
  aes(x = dest, y = total_orig_dest, color = origin, fill = origin) +
  geom_bar(stat = "identity", position = "dodge") +# por defecto viene el stacked bar plot
  geom_label(mapping = aes(label = total_orig_dest), position = position_dodge(width=0.9) , color = "black")
