# -*- coding: utf-8 -*-
"""1_Distribuciones_de_probabilidad_en_r.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uqxBX8ZuOC45giCC3qNhYwUXCsKERh3J

<a href="https://colab.research.google.com/github/majorquev/DBDC_202507_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/Clase8/1_Distribuciones_de_probabilidad_en_r.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 6: Distribuciones de probabilidad

**Autor:** Miguel Jorquera Viguera.<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales<br>
**E-mail ayudante:** rumorale1@gmail.com

En R podemos obtener valores tanto de las funciones de densidad, distribución de probabilidad, cuantiles de una distribución o bien generar valores aleatorios de diversas distribuciones paramétricas.
Casi todas las distribuciones que se encuentran implementadas en la librería base de R se referencian de la misma manera.

* Funciones de densidad (PDFs) comienzan con la letra “d.”
* Funciones de distribución acumulada comienzan con la letra “p.”
* Funcioenes que retornan quantiles de una distribución comienzan con la letra “q.”
* Funciones que generan valores aleatorios comienzan con la letra“r.”

Por defecto, en R contamos con una amplia variedad familias de distribuciones enre las que destacan las siguientes.



**Distribution**| **R name**| **additional arguments**
-----| -----| -----
beta |`beta` |shape1, shape2, ncp
binomial| `binom`| size, prob
Cauchy|`cauchy` |location, scale
chi-squared| `chisq`| df, ncp
exponential| `exp` |rate
F| `f` |df1, df2, ncp
gamma |`gamma` |shape, scale
geometric |`geom` |prob
hypergeometric| `hyper`| m, n, k
log-normal| `lnorm` |meanlog, sdlog
logistic |`logis` |location, scale
negative| `binomial`| nbinom size, prob
normal |`norm` |mean, sd
Poisson| `pois`| lambda
signed rank |`signrank`| n
Student’s t| `t`| df, ncp
uniform |`unif`| min, max
Weibull| `weibull`| shape, scale
Wilcoxon |`wilcox`|m, n

# I) Distribución normal

## Función de densidad
$$f(x) = \frac{1}{\sqrt{2 π \sigma^2}} e^{-\frac{1}{2\sigma^2}(x - \mu)^2}$$

## En R...

* `dnorm(x, mean = 0, sd = 1, log = FALSE)`: Evalúa la función de densidad.
* `pnorm(q, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)`: Calcula la probabilidad acumulada (función de distribución).
* `qnorm(p, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)`: Calcula los quantiles de la distribución. (Función inversa de la función de distribución de probabilidad).
* `rnorm(n, mean = 0, sd = 1)`: Genera muestras aleatroias.




**P1.** Se sabe que la estatura de la población adulta de sexo masculino chilena sigue una distribución normal con media 171,8 cms y una desviación estándar de 5cms

**a)** ¿Cuál es la probabilidad de encontrar de que una persona hombre  adulta tenga una estatura
menor o igual a 160 cms?
"""

# pnorm()
#?pnorm

# Dist.Normal
prom <- 171.8
desv <- 5.0
q <- 160 # pto.

p<-pnorm(q, mean = prom, sd = desv)
p # prob.acum.
# Hay una prob de un 0.9% de encontara una persona adulta..... con estatura menor o igual a 160 cms.
# Es decir, se espera que de cada 100 personas adultas...., approx. 1 de ellas tenga estatura menor o igual a 160 cms.

?pnorm

"""  
**b)** ¿Cuál es la probabilidad de encontrar de que una persona adulta tenga una estatura mayor  a 160 cms?
  
"""

#P(estatura > 160) = 1- P(estatura <= 160)
1-pnorm(160, mean = 171.8, sd = 5) # 99% de prob de que un adulto Chileno mida más de 1.60.

#NOTA
# lower.tail
pnorm(160, mean = 171.8, sd = 5, lower.tail = F)

"""**c)** ¿Cuál es la probabilidad de encontrar una persona con estatura entre 180cms y 190 cms?"""

q1<-180
q2<-190
p<-pnorm(q2, mean = prom, sd = desv) - pnorm(q1, mean = prom, sd = desv)
p
# Se espera que 5 de cada 100 personas adultas.... midan entre 180 y 190 cms.

?pbinom

"""**d)** ¿Cuál es la estatura que corresponde al percentil 90?"""
# = Cual es la estatura que acumula el 90 % de probabilidad

p<-.9
#q=?

q<-qnorm(p, mean = prom, sd = desv)
q
# El 90% de la población tiene una estatura menor o igual a 178.2
# =Que la proba. de que una persona adulta... tenga estatura menor o igual a 178.2, es de un 90%.

"""**d)**  Genere una muestra aleatoria de tamaño 1000 y guárdela en un vector llamado _estaturas_, provenientes de una distribución normal con media 171,8 y desviación estandar igual a 5."""

# estaturas
set.seed(2020) #semilla

estaturas <- rnorm(n = 1000, mean = 171.8, sd = 5)

estaturas

length(estaturas)
mean(estaturas)
sd(estaturas)

"""**e)** Mediante la función _hist()_ y la función _curve()_  genere un histograma de la muestra creada y añada la curva de distribución normal con la media y desviación estandar reales."""

## NOTA
hist(estaturas, freq = F, breaks = 20)
curve(dnorm(x,mean = 171.8, sd = 5), add = T, col = "red" )
curve(dnorm(x,mean = mean(estaturas), sd = sd(estaturas)), add = T, col = "blue" )

library(ggplot2)
library(dplyr)
df <- data.frame(est = estaturas)
head(df)

(mu_est <- mean(estaturas))
(sd_est <- sd(estaturas))

# Notar que en un histograma podemos visualizar los conteos o las frecuencias relativas.
df %>%
  ggplot() +
  aes(x = est) +
  geom_histogram(
    bins = 20,
    fill = "white",
    color = "black",
    mapping = aes(y = after_stat(density))
  ) +
  stat_function(
    fun = dnorm,
    args = list(mean = 171.8, sd = 5),
    col = "red" # la densidad normal con los parametros reales
  ) +
  stat_function(
    fun = dnorm,
    args = list(mean = mu_est, sd = sd_est),
    col = "blue" # la densidad normal con los parametros reales
  ) +
  geom_density(col = "green") # Estimación "no paramétrica" de la densidad de nuestra muestra. (Ref. Estimación por Kernels)

"""# II)Distribucion binomial
## Contexto
Cuando una variable aleatoria representa la cantidad de éxitos en $n$ ensayos independientes de tipo Bernoulli (0 o 1), se dice que dicha variable sigue una distribución binomial.

## Función de probabilidad


$$p(x) = {n\choose x}p^x(1-p)^{n-x}$$
Donde $n$ es el total de ensayos realizados y $x$ es la cantidad de éxitos observados y $p$ es la probabilidad de éxito del evento de interés.

## En R...

* `dbinom(x, size, prob, log = FALSE)`: Evalúa la función de masa. En el caso discreto corresponde a la probabilidad del evento.
* `pbinom(q, size, prob, lower.tail = TRUE, log.p = FALSE)`: Calcula la probabilidad acumulada.
* `qbinom(p, size, prob, lower.tail = TRUE, log.p = FALSE)`: Retorna cuantiles de la distribución.
* `rbinom(n, size, prob)`: Genera muestras aleatorias.

**P2.** Suponga que un spot publicitario de un artículo tiene una tasa de efectividad de 20% sobre una determinada población.

**a)** Suponga que se logra llegar con el spot a 100 personas. ¿Cuál es la probabilidad de que
 al menos 30  personas compren el artículo ofrecido?
"""

# Identifiquemos algunos elementos como
# Experimento : Hacer llegar el spot a las 100 personas y registrar el número de clientes que efectivamente compraron el artículo.
# Variable aleatoria : X: "el número de clientes (de los 100) que compraron el artículo"
# Espacio muestral : {0,1,2,...,100}
#-------parámetros de pbinom ---------
#size (n): 100
#prob (p): 0.2 (20%)
#q >= 30 => no (q<30) => p = 1-p(q<30) = 1-p(q<=29)
1-pbinom(q = 29 , size = 100, prob = 0.2)# 11%°
pbinom(q = 29 , size = 100, prob = 0.2, lower.tail = F)

# ¿Cuál es la probabilidad de que exactamente 30 personas compren el artículo ofrecido?
dbinom(30 , size = 100, prob = 0.2)
pbinom(30 , size = 100, prob = 0.2) - pbinom(29 , size = 100, prob = 0.2)

"""**P3.** En una localidad se sabe que el 70% de las casas tienen un televisor.  Se quiere realizar una encuesta a 8 casas ¿cuál es la probabilidad de que 6 o más de ellas tengan televisor?"""

# size = 8
# prob = 0.7

"""## Lanzando una moneda
**P4** Supongamos que una **honesta** se lanza 14 veces y se anota el número veces que se obtuvo cara.

**a)** ¿Cuál es la probabilidad de obtener exactamente 4 caras? ¿y al menos 10?
"""

#size = n = 14, y prob = p = 0.5 ?

# P(X >= 10)

"""  
**b)** Si se repite el experimento 5 veces.


*   ¿Qué proporción de caras se debería esperar?¿y si se repite más veces?
*   ¿En qué % de casos se obtuvo exactamente 4 caras? ¿ y si se repite más veces?


 Utillice la función rbinom para simular el experimento 100 veces.
"""

# simulamos un experimento binomial



# Pero si queremos visualizar las frecuencias relativas observadas?
# Adicionalmente nos interesaría poder visualizar la función de masa de probabilidad.



"""# III) Distribución poisson
## Contexto
Usualmente una variable aleatoria poisson, representa la cantidad de eventos registrados en un interval fijo de tiempo con una cierta tasa de ocurrencia.
## Función de probabilidad

$$p(x) = \lambda^x \dfrac{e^{-\lambda}}{x!}$$

Donde $\lambda$ corresponde a la tasa de ocurrencia y $x$ la cantida de eventos observados.

## Funciones en R
 * `dpois(x, lambda, log = FALSE)`
 * `ppois(q, lambda, lower.tail = TRUE, log.p = FALSE)`
 * `qpois(p, lambda, lower.tail = TRUE, log.p = FALSE)`
 * `rpois(n, lambda)`
"""



"""** P5. ** Suponga que en un restaurant de comida se tiene una tasa de llegada de clientes de 2 clientes por cada 3 minutos en promedio.
¿Cuál es la probabilidad de que 5 o más clientes lleguen en un período de 9 minutos?.

"""

# La tasa de éxito en una dist. poisson es el parámetro lambda
# Dada la info, se tiene una tasa de 6 clientes cada 9 minutos

"""**P6.** Se sabe que la tasa de falla en la elaboración de ampolletas sigue una distribución poisson, con una tasa de falla de 3 ampolletas defectuosas por semana.
¿Cuál es la probabilidad de que al cabo de un mes se genere un total de 20 ampolletas defectuosas o más?


"""

# lambda = 3*4 = 12 ampolletas defectuosas por mes

