# -*- coding: utf-8 -*-
"""Clase6_1_Estadisticos_descriptivos_y_correlación.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GFegLecYwfarZQokMlZisb139iXMdg36

<a href="https://colab.research.google.com/github/majorquev/DBDC_202507_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/Clase6/Clase6_1_Estadisticos_descriptivos_y_correlaci%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""

options(repr.plot.width=8, repr.plot.height=6)

"""# Parte 4: Análisis descriptivo con R

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales<br>
**E-mail ayudante:** rumorale1@gmail.com


Una de las fases principales dentro de un proyecto de Data Science, corresponde al análisis exploratorio de datos. Es en esta etapa donde se realizan los primeros hallazgos, se verifica la calidad de los datos, se detectan anomalías, se identifican patrones y se realizan preguntas claves que permitan comenzar a realizar inferencias , o si es el caso, comenzar a plantear modelos con fines predictivos.

## I. Estadísticos descriptivos
### a) Medidas de posición
Corresponden a valores que nos permiten dividir nuestra muestra en conjuntos con aproximadamente la misma cantidad de individuos.
### b) Medidas de tendencia central
Corresponden a medidas a las que tienden “agruparse” los datos de la muestra .
### c) Medidas de dispersión
Medidas que cuantifican el nivel de heterogeneidad de una variable numérica.


En R contamos con funciones para lo anterior:

 - summary(): Por defecto entrega estadísticos de posición (cuartiles), min, max y media.
 - quantiles(): Retorna uno o varios percentiles de interés.
 - mean(): Calcula la media de un vector numérico.
 - median(): Calcula la mediana de un vector numérico.
 - sd(): Retorna la desviación estándar muestral.
 - var(): Retorna la varianza muestral.

### I.1. Descripción de data _mpg_

Analicemos el rendimiento en ciudad en función de los estadísticos descriptivos más conocidos.

"""

library(ggplot2)
library(dplyr)

data(mpg)
mpg %>%
  dplyr::count()
head(mpg)
# cyl: cilindros
# displ: Engine displacement, in lt "cilindrada"
# drv: traccion
# cty: city miles miles per gallonb
# hwy: highway miles per gallon
# fl: fuel type
# class: "type" of car

"""### Media, Mediana  y percentiles
Los percentiles, en particular la mediana corresponden a estadísticos de posición, ya que nos permiten "ubicarnos" dentro de la muestra que estamos analizando y nos dan una primera idea sobre la distribución de los datos a analizar. Por su parte la media (aritmética) corresponde a un estadístico de tendencia central.
"""

# describamos el rendimiento en carretera en función de los estadísticos de pos., tendencia central  y dispersión

# promedio
print(paste("El promedio de hwy es: ", mean(mpg$hwy))) # Est. de tendencia central
# mediana
print(paste("La mediana de hwy es: ", median(mpg$hwy))) # Est de posición. (es el el percentil 50)
# percentiles
quantile(mpg$hwy, probs = 0.5)
# Ambos a la vez
quantile(mpg$hwy, probs = c(0.25, 0.5) )
# A modo de ejemplo, se observa que el 25% de los autos analizados tiene un rendimiento en carretera menor o igual a 18 mpg.

# Guido: Total de autos analizados
nrow(mpg)



# recordar que podemos visualizar los cuartiles en un boxplot
mpg %>%
  ggplot() +
  aes(y = hwy) +
  geom_boxplot()

quantile(mpg$hwy, probs = c(0.25,0.5,0.75))

"""### Medidas de dispersión
Rango, desviación estándar  y rango intercuartílico. Son medidas que buscan cuantificar el nivel de dispersión o heterogeneidad de nuestra muestra.
"""

# medidas de dispersión ---------------

# Rango
max(mpg$hwy)
min(mpg$hwy)
max(mpg$hwy) - min(mpg$hwy)

# NOTA:
# ¿Cómo saber cuál(es) es(son) el(los) auto(s) que tiene(n) el menor/mayor rendimiento en carretera?

# OP1: ojo que con este approach solo retornamos un registro para el min/max rendmiento
id_min <- which.min(mpg$hwy)
id_max <- which.max(mpg$hwy)

id_min
id_max

mpg[id_min,]
mpg[id_max,]

# OP2 Usando dplyr
mpg %>%
  filter(hwy == min(hwy) | hwy == max(hwy))

mpg %>%
  filter(hwy %in% c(min(hwy),max(hwy)) )

mpg %>%
  ggplot() +
  aes(y = hwy) +
  geom_boxplot()

# Rango Inter-cuartílico (corresponde al "rango" del 50% de la muestra - el que está comprendido entre Q1 y Q3-)
IQR(mpg$hwy)
quantile(mpg$hwy, .75) - quantile(mpg$hwy, .25)

# Una obs se considera "extrema" si si valor está por sobre (debajo) 1.5 veces el rango intercuartílico (RI = Q3- Q1) desde  Q3 (Q1)
IQR(mpg$hwy)
quantile(mpg$hwy, .25) - 1.5*IQR(mpg$hwy)
quantile(mpg$hwy, .25) - 1.5*(quantile(mpg$hwy, .75) - quantile(mpg$hwy, .25))
quantile(mpg$hwy, .25) - 1.5*quantile(mpg$hwy, .75) + 1.5*quantile(mpg$hwy, .25)
2.5*quantile(mpg$hwy, .25) - 1.5*quantile(mpg$hwy, .75)

# lim inf 1.5*IQR (por "debajo")
mpg %>%
  filter(hwy <= quantile(mpg$hwy, .25) - 1.5*IQR(hwy))

# lim sup 1.5*IQR (por "arriba")
mpg %>%
  filter(hwy >= quantile(mpg$hwy, .75) + 1.5*IQR(hwy))

# Varianza y Desviación estándar
var(mpg$hwy) # "En promedio, los rendimientos en carretera se desvían de la media en 35.5mpg^2"

# Desv. est
sqrt(var(mpg$hwy))
sd(mpg$hwy) #"En promedio, los rendimientos en carretera se desvían de la media en 6 mpg (millas por galon)"

# Coef de variación = desviación estandar / |promedio|

# Salarios de dos grupos de personas.
# Grupo A: sd = $500.000
# Grupo B: sd = $500.000

#¿Son estos dos grupos igual de homogéneos/heterogéneos?
# Grupo A: sd = $500.000 , mean =  $700.000
# Grupo B: sd = $500.000 , mean =  $5.000.000

# Coef de variación = desviación estandar / |promedio|
500000/abs(700000)
500000/abs(5000000)

"""## II. Correlación de variables

Las medidas de correlación buscan cuantificar el nivel de asociación que existe entre dos variables. Uno de los coeficientes más populares para medir la dependencia lineal entre dos variables corresponde al coeficiente de correlación de Pearson.

Matemáticamente, el coeficiente de correlación de Pearson entre dos variables aleatorias X e Y se define como

$$\rho = \dfrac{\mathbb{E}[(X-\mu_X)(Y-\mu_Y)]}{\sqrt{\sigma^2_X\sigma^2_Y}}$$

Este coeficiente varía entre -1 y 1, y alcanza dichos valores siempre que X e Y formen una recta.

Exploremos algunos ejemplos

**¿Cómo es la relación entre el rendimiento en carretera y el tamaño del motor?**
"""

# Gráficamente x = displ, y = hwy
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point()

# podemos añadir "recta" de tendencia
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  geom_smooth(method = "lm")

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  geom_smooth()

cor(mpg$displ, mpg$hwy)

ggplot(mpg, aes(x = 1:234, y = 1:234)) +
  geom_point() +
  geom_smooth()

cor(1:234, 1:234)

ggplot(mpg, aes(x = 1:234, y = 234:1)) +
  geom_point() +
  geom_smooth()

cor(1:234, 234:1)

vx = 1:234
vy <- (1:234 + 234:1)/2 + .5

ggplot(mpg, aes(x = vx, y = vy)) +
  geom_point() +
  geom_smooth()

cor(vx, vy)

"""Podemos seleccionar las columnas *mpg,disp,hp,drat,wt,qsec* y generar un gráfico de dispersión para cada par de ellas, con la función plot() del paquete _base_."""

data(mtcars)
head(mtcars)

#Podemos graficar algunas de las variables de interés
aux <- mtcars %>%
    select(mpg,disp,hp,drat,wt,qsec)

aux %>%
  dplyr::count()

head(aux)

options(repr.plot.width=16, repr.plot.height=9)
plot(aux)

"""### P1. Comando cor
Investigue el comando cor y utilícelo con la selección previa de columnas.
¿Qué observa?

### P2. De acuerdo a  la documentación, cambie el método de cálculo a "spearman"
¿Que observa?
"""

cor(aux) # por defecto calcula correlación de pearson

"""## NOTA: parámetro method de la función cor()"""

?cor

set.seed(123) # Semilla para generar númeos aleatorios
x <- rnorm(100) # variable X
e <- rnorm(100, sd = .5) # error aleatorio
# Modelar y como funcion de x y un error aleatorio
# y = f(x) + e
y <- 1+ 3*x^3 + e

A <- data.frame(x = x, y = y)

"""$y = f(x) + \epsilon$ \\
$y = 3x^{3} + 1 + \epsilon$
"""

# Gráficamente la relación de x e  y

A %>%
    ggplot() +
    aes(x = x, y = y) +
    geom_point()

# parámetro method de la función cor()
cor(A$x,A$y) # Pearson por defecto
cor(A$x,A$y, method = "spearman")

set.seed(123) # Semilla para generar númeos aleatorios
x <- rnorm(100) # variable X
e <- rnorm(100, sd = .5) # error aleatorio
# Modelar y como funcion de x y un error aleatorio
# y = f(x) + e
y <- 1+ 3*x + e

A <- data.frame(x = x, y = y)

# Gráficamente la relación de x e  y

A %>%
    ggplot() +
    aes(x = x, y = y) +
    geom_point()

###$y = f(x) + \epsilon$ \\
###$y = 3x + 1 + \epsilon$

# parámetro method de la función cor()
cor(A$x,A$y) # Pearson por defecto
cor(A$x,A$y, method = "spearman")

"""## Gráfico de correlación"""

#install.packages("corrplot")
library(corrplot)

# función corrplot()

"""### P3. Opciones de corrplot
Identifique (en la documentación de la función corplot) otros métodos de visualización
"""

matriz_cor <- cor(aux)
matriz_cor

# Función corplot()
# podemos modificar el parámetro "method"
corrplot(matriz_cor)
