# -*- coding: utf-8 -*-
"""Clase_2_01_matrices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UelZHdJDEOIYWCpWclpMpYSMBKjlc8wy

<a href="https://colab.research.google.com/github/majorquev/DBDC_202507_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/Clase2/Clase_2_01_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales <br>
**E-mail ayudante:** rumorale1@gmail.com



### 3.2 Matrices

En R, así como en otros lenguajes de programación, una matriz es básicamente un arreglo bi-dimensional, donde las entradas horizontales se entienden como filas y las verticales como columnas. Es posible imaginar una matriz como un arreglo de vectores como columnas (o filas) del mismo largo.

 * ¿Qué se guarda en una matriz?<br>
    Sólo datos de un mismo tipo.
     
 * ¿Cómo se declara una matriz?<br>
    Se puede definir de varias maneras, indicando los elementos que la componen, o combinando vectores como filas o columnas.

 * ¿Cómo se accede a sus elementos?<br>
    Indicando la posición del vector fila, seguido de la posición del vector columna (como es usual).
"""

# 3.2 Matrices ------------
#?matrix de dos filas y 3 columnas, parametros ncol, nrow y byrow
# recibe un vector de elementos
A <- matrix(c(1,1,2,3,5,8), nrow = 2, ncol = 3)
A

B <- matrix(c(1,1,2,3,5,8), nrow = 2, ncol = 3,  byrow = T)
B

# clase y atributo dim
class(A)
dim(A)
nrow(A)
ncol(A)

# Genere dos vectores del mismo largo y forme una matriz.
c1 <- c(1,2,3)
c2 <- c(9,8,7)

f1 <- c("A","B","B")
f2 <- c("X","Y","Z")

# funciones cbind() [une vectores como columnas]
# y rbind() [une vectores como filas] (pensadas para matrices)
#?cbind


(M1 <- cbind(c1,c2))
(M2 <- rbind(f1,f2))

# NOTA: Podemos añadir una fila/columna a una matriz existente
f3 <- c("M", "N", "K")
# Queremos añadir f3 a M2.
rbind(M2,f3)
M2

# Si quiero actualizar M2 y que contenga a f3.
M2 <- rbind(M2,f3)
M2

# si combinamos vectores de distinto largo?
# R recicla valores (recordar explicación)

f4 <- c(1,2)
 M2

rbind(M2,f4)

# función diag para la definición de matrices diagonales
#?diag
diag(1:5)

# Podemos acceder a los elementos de una matriz
# indicando la posición de la fila y la columna de la casilla correspondiente.
# Ejemplo:
M2

# quiero rescatar el elemento "(2,1)"
M2[2,1]

# CUIDADO:No es lo mismo que
M2[c(2,1)] # Acá R interpreta M2 como el vector que define a todas las columnas de la matriz.

# Para acceder a una fila completa
M2[2,]

# Para acceder a una columna completa
M2[,2]

M2

#Recordemos que podemos actualizar elementos de un vector como:

# quiero cambiar el "Z" por un "W" (el Z de la pos (2,3))
M2[2,3] <- "W"

M2

# NOTA: Nombres de filas y columnas en una matriz
# antes en un vector podíamos acceder a los nombres con names()
# Ahora colnames() y rownames() para nombres de columnas y filas respectivamente.
rownames(M2)
colnames(M2) <- c("c1","c2","c3")

M2

# Acceso mediante nombres

# Acceso mediante nomnbres
# Elemento de la segunda fila tercera columna (2,3)

M2["f2","c3"]

M2

# Una fila/columna completa
M2["f2",]
M2[,"c3"]

# NOTA: Podemos rescatar más de una fila/columna indicando un vector de posiciones/nombres de filas/columnas
# Ej: Quiero seleccionar solo las columnas 1(c1) y 3 (c3)
M2[,c(1,3)] # Indicando posiciones de las columnas de interés
M2[,c("c1","c3")] # Indicando nombres de las columnas de interés

M2[c(1,3),] # Indicando posiciones de las filas de interés
M2[c("f1","f3"),] # Indicando nombres de las filas de interés

M2

# Acceso mediante "indicatrices" lógicas
#Quiero obtener los elementos (1,1) y (3,3) de M2
# 1: Crear una matriz de 3x3 con TRUE en dichas posiciones y FALSE en las restantes.
M_ind <- matrix(c(T,F,F,F,F,F,F,F,T), nrow = 3, ncol = 3, byrow = T)
M_ind

M2[M_ind]

M2

# Podemos evaluar las casillas de una atriz mediante sentencias lógicas
M2[c(T,F,F),]

M2[M2[,"c1"] == "A", ]

"""**Álgebra de matrices**

Las operaciones suma (resta) y ponderación por escalar se llevan cabo mediante los mismos operadores utilizados para valores numéricos y vectores (+,-,*, /). Para multiplicar matrices en cambio, se utiliza el operador %*%, mientras que para invertirlas se utiliza la función solve(), t() para transponer y det() para el cálculo del determinante en el caso de matrices cuadradas.
"""

# transponer una matriz
M2
t(M2)

# 3.2 Álgbra de matrices  ------------
# Ejemplo simple de álgebra de matrices

A;B

# Multiplicación de matrices
A * B

A %*% t(B)

# podemos calcular determinantes
# ?det
det(A %*% t(B))

# Podemos invertir matrices
# ?solve
solve(A %*% t(B))