# -*- coding: utf-8 -*-
"""Clase7_1_reglas_de_asociacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i25-kqT6MfaHfXosUGM14LOKZx2qSTlT

<a href="https://colab.research.google.com/github/majorquev/DBDC_202507_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/Clase7/Clase7_1_reglas_de_asociacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 4: Reglas de asociación


**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales<br>
**E-mail ayudante:** rumorale1@gmail.com

Las reglas de asociación nos permiten identificar relaciones entre variables a través de grandes datasets. Es posible cuantificar que tan "fuerte" es la relación obtenida mediante diversas métricas de interés, entre las cuales se destacan el _lift_, _support_ y _confidence_ de una regla.

Para más detalles sobre la definición y algoritmo de generación de las reglas refiérase a la presentación de la clase 7 de este curso.
"""

#install.packages("arules")

library(arules)
library(dplyr)
data(Groceries)
class(Groceries)

inspect(head(Groceries, 6))

Groceries

class(Groceries)

?transactions

inspect(head(Groceries, 6))

# Numero de items por observación mediante comndo size
size(head(Groceries,6))

mean(size(Groceries))

#LIST convierte las trasacciones a una lista (con mayusculas)
lista <- LIST(head(Groceries,6))

lista
class(lista)
str(lista)

class(Groceries)

# eclat() para generar los itemsets frecuentes. theta = 0.02
frequentItems <- eclat(Groceries,
                        parameter = list(supp = 0.02)
                       ) # se calcula el support para items frecuentes

frequentItems
class(frequentItems)
inspect(frequentItems)

itemFrequencyPlot(Groceries,
                  topN=10,
                  type="relative",
                  main="Item Frequency") #podemos graficar los items frecuentes

"""## ¿Cómo determinamos las reglas?"""

rules <- apriori(data = Groceries, #debe ser del tipo "transactions"
                 parameter = list(supp=0.01, conf = 0.08),
                )
rules

0.01037112/0.02796136
0.37090909

# {hard cheese} => {whole milk}
# Support: 0.01006609 = 1%
# Hard cheese y whole milk tienen una tasa de ocurrencuia conjunta del 1%, es decir en el 1% de las trasancciones se suele llevar ambos productos en la misma compra
# Confidence: 0.41078838 = 41%
# La probabildad de que se lleve leche, dado que se está llevando queso, es de un 41%.
# O bien, del total de transacciones que llevan queso, en un 41% de ellas, también se lleva leche.

0.01006609/0.02450432

length(rules)
class(rules)
inspect(rules)

df_rules1 <- DATAFRAME(rules)

df_rules1 %>%
  filter((LHS == "{beef}" & RHS == "{whole milk}") |
         (RHS == "{beef}" & LHS == "{whole milk}") )

df_rules1 %>%
  dplyr::filter(lift<1)

df_rules1 %>%
  dplyr::filter(lift>1) %>%
  dplyr::count()

df_rules1 %>%
  dplyr::filter(lift==1)

#Lift de beef -> Leche es 1.58
# Al llevar beef, la probabilidad de que se lleve leche, aumenta 1.58 veces.
# Al llevar beef, la probabilidad de que se lleve leche, aumenta en un (1.58-1)*100 %, aumentó en un 58%

# Al llevar leche, la probabilidad de que se lleve beef, aumenta 1.58 veces.
# Al llevar leche, la probabilidad de que se lleve beef, aumenta en un (1.58-1)*100 %, aumentó en un 58%

## Y si queremos buscar con qué combinar un producto determinado, por ejemplo leche
rules <- apriori( data = Groceries,
                  parameter =list (supp=0.02,conf = 0.08, minlen = 2),
                  #appearance = list(default="rhs", lhs ="whole milk"),
                  control = list (verbose=F))

class(rules)
rules

inspect(rules)

## Y si queremos buscar con qué combinar un producto determinado, por ejemplo leche
rules <- apriori( data = Groceries,
                  parameter =list (supp=0.02,conf = 0.08, minlen = 2),
                  appearance = list(default="rhs", lhs ="whole milk"),
                  control = list (verbose=F))

class(rules)
rules

inspect(rules)

rules_conf <- sort(rules,
                   by="lift",
                   decreasing=TRUE) # ordenando por confidence rules.

rules
inspect(rules_conf)

"""## Transformación a objetos de clase transaction




"""

?transactions

## Example 1: creating transactions form a list (each element is a transaction)
     a_list <- list(
       c("a", "b", "c"),
       c("a", "b"),
       c("a", "b", "d"),
       c("c", "e"),
       c("a", "b", "d", "e")
     )

     ## Set transaction names
     names(a_list) <- paste("Tr", c(1:5), sep = "")
     a_list

## Use the constructor to create transactions
     ## Note: S4 coercion does the same trans1 <- as(a_list, "transactions")
     trans1 <- transactions(a_list)
     trans1
     inspect(trans1)

## Example 2: creating transactions from a 0-1 matrix with 5 transactions (rows) and
     ##            5 items (columns)
     a_matrix <- matrix(
       c(
         1, 1, 1, 0, 0,
         1, 1, 0, 0, 0,
         1, 1, 0, 1, 0,
         0, 0, 1, 0, 1,
         1, 1, 0, 1, 1
       ),
       ncol = 5
     )

     ## Set item names (columns) and transaction labels (rows)
     colnames(a_matrix) <- c("a", "b", "c", "d", "e")
     rownames(a_matrix) <- paste("Tr", c(1:5), sep = "")

     a_matrix

## Create transactions
     trans2 <- transactions(a_matrix)
     trans2
     inspect(trans2)

## Example 4: creating transactions from a data.frame with
     ## transaction IDs and items (long format)
     a_df3 <- data.frame(
       TID =  c(1, 1, 2, 2, 2, 3),
       item = c("a", "b", "a", "b", "c", "b")
     )
     a_df3

trans4 <- transactions(a_df3, format = "long", cols = c("TID", "item"))
trans4
inspect(trans4)

## Example 3: creating transactions from data.frame (wide format)
     a_df <- data.frame(
       age = as.factor(c(6, 8, NA, 9, 16)),
       grade = as.factor(c("A", "C", "F", NA, "C")),
       pass = c(TRUE, TRUE, FALSE, TRUE, TRUE)
     )
     ## Note: factors are translated differently than logicals and NAs are ignored
     a_df

## Create transactions
     trans3 <- transactions(a_df)
     inspect(trans3)