# -*- coding: utf-8 -*-
"""Clase_2_03_mini_taller.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CUmz6GKEhSwAA5NcYwZEDdBvpgQcFKZm

<a href="https://colab.research.google.com/github/majorquev/DBDC_202507_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/Clase2/Clase_2_03_mini_taller.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Mini taller 1**
**Autor:** Miguel Jorquera Viguera <br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales<br>
**E-mail ayudante:**  rumorale1@gmail.com<br>
"""



"""
Los dataframes corresponden a uno de los objetos más utilizados en R para analizar datos tabulares,
por lo que se hace necesario en muchos casos realizar consultas a los datos que contiene un dataframe,
(filtros, cruces de tablas, creación de columnas, etc). Por ahora veremos una de las formas más "primitivas" para la manipulación de un data.frame.

Para ello consideremos el siguiente ejercicio.

**Paso 1**
Mediante la función rnorm(), genere una muestra aleatoria de 100 datos , con media 21 y desviación estándar 8 (más adelante veremos esto con un poco más de detalle), y guárdela en una variable llamada temp.

"""

# 5.3 Mini taller --------
# Paso 1
temp <- rnorm(n = 100, mean = 21, sd = 8)
temp

# Dejar como parámetro el largo del vector temp

"""**Paso 2**

Genere un vector llamado _dia_ del mismo largo que que *temp*, que contenga los días consecutivos de la semana, partiendo del lunes. (utilice la función _rep()_ )
"""

# Paso 2
#dia <- rep(c("L","M","W","J","V","S","D"), 100 ) repite el vector de largo7, 100 veces. Genera un vector resultante de largo 700

"""**Paso 3**

Genere un vector llamado _est_, del mismo largo que _temp_, que en el primer tercio contenga el valor "E1", en el segundo tercio "E2", y en el tercer tercio "E3". Por ejemplo, si _temp_ tuviese 10 datos, el vector _est_ se vería como


<center> _est_ = (E1,E1,E1,E2,E2,E2,E3,E3,E3,E3) </center>
"""

# Paso 3

"""**Paso 4**

Genere un vector llamado _lluvia_ del mismo largo que _temp_, que sea TRUE en las posiciones en que _temp_ sea menor que 20, y FALSE en caso contrario.
"""

# Paso 4

"""**Paso 5**

Finalmente cree un data frame llamado _precipitaciones_ con las siguientes columnas:<br>

*Dia_semana* (con los valores del vector _dia_)<br>
*Temperatura* (con los valores del vector _temp_)<br>
*Llueve* (con los valores del vector _lluvia_)<br>
*Estacion* (con los valores del vector _est_)<br>
"""

# Paso 5

"""#### Strings como factores
Cuando en R se declara una variable como factor, internamente se codifican sus categorías con valores 0 o 1. Por ejemplo, para las variables _Dia_ y _Estacion_ podemos generar sus matriz de diseño, indicando un 1 si el día (o estación) corresponde a la nueva columna generada, 0 si  no:

 |Dia |Temperatura    |Llueve| Estacion| | Dia.L|Dia.M|Dia.W|Dia.J|Dia.V|Dia.S|Dia.D|Est.1|Est.2|Est.3|
 |----|------------   |------|---------| |---   |---  |---  |---  |---  |---  |---  |---  |---  |---  |
 |L	  |16.300201      |TRUE  |	E1     | |1     |0    |0    |0    |0    |0    |0    |1    |0    |0    |
 |M   |21.042854      |FALSE |	E1     | |0     |1    |0    |0    |0    |0    |0    |1    |0    |0    |
 |J	  |31.256043      |FALSE |	E3     | |0     |0    |0    |1    |0    |0    |0    |0    |0    |1    |
 |S	  |40.083514      |FALSE |	E3     | |0     |0    |0    |0    |0    |1    |0    |0    |0    |1    |

 Cuando se quiere generar un resumen de una variable categórica, o cuando se quiere incluir una variable de este tipo en el entrenamiento de un modelo será necesario declarar dicha variable como factor.
"""

#podemos volver a coercionar las columnas a clase factor,  con la función as.factor

# Un poco de exploración --------------------------------
# ¿Cuál es la temperatura promedio cuando llovió?

# ¿Cuál es la temperatura promedio cuando NO llovió?



#Lo mismo pero sólo de los registros de E1

# ¿Qué día era cuando se alcanzó la mínima temperatura?¿y la ,máxima?
#La función which.min #o .max . retorna la posición donde se alcanza el min/max de un vector.

# opcion 1

# opcion 2

# Una forma de eliminar registros en vector

# POdemos eliminar los registros de posición 3 y 4

# Si queremos ver esa misma fila de la tabla precipitaciones.


# Se sabe que la Estación E3 falla todos los días domingo, por lo que se quiere eliminar tales registros de la tabla. Elimínelos!

dim(precipitaciones)

"""## 5.4 Cómo guardar ambiente de trabajo o variables definidas en el

### Directorio de trabajo

El directorio de trabajo corresponde a la ubicación en el sistema de archivos, desde donde la sesión de R podrá acceder directamente para guardar o cargar datos.

"""

# para saber en qué directorio se está trabajando

# para cambiar el directorio de trabajo

"""### Formato rds

Una manera de guardar variables creadas en el ambiente de la sessión de R, es mediante la utilización del formato *.rds. Este formato permite guardar los objetos declarados y leerlos rápidamente en cualquier otra sesión que se inicie posteriormente. Es últil por ejemplo para guardar en disco modelos entrenados para ser utilizados para predicciones futuras.

"""

# Función saveRDS() # Guardar
# guarde en el directorio actual el dataframe _precipitaciones_

# readRDS()  Leer, pero ojo que es necesario asignar  a una variable

"""### Formato RData

Cuando se quiere guardar el ambiente de trabajo completo, o bien un mayor número de objetos ya creados, se puede utilizar la función _save_

"""

# Función save para guardar uno o más objetos del ambiente.

# Eventualmente podemos "cargar " a sesión, con la función load()